import json
import os

metadata_updates = {
    '1. Dhamir__1a': {
        'desc_bn': 'তিনি / সে (১ জন পুরুষ, পৃথক সর্বনাম)',
        'jenis_bn': 'মুনফাসিল (পৃথক)',
        'desc_ms': 'Dia (1 orang lelaki, terpisah)',
        'jenis_ms': 'Munfashil (Terpisah)',
        'desc_fr': 'Il / Lui (3e personne singulier masculin, pronom détaché)',
        'jenis_fr': 'Munfashil (Détaché)',
        'desc_de': 'Er (3. Person Singular Maskulinum, getrenntes Pronomen)',
        'jenis_de': 'Munfashil (Getrennt)',
        'desc_ur': 'وہ (ایک مرد، ضمیر منفصل)',
        'jenis_ur': 'منفصل (علیحدہ)',
        'desc_hi': 'वह (१ पुरुष, अलग सर्वनाम)',
        'jenis_hi': 'मुन्फ़सिल (अलग)',
        'jenis_en': 'Munfashil (Detached)'
    },
    '1. Dhamir__1b': {
        'desc_bn': '...-তার / তাকে (১ জন পুরুষ, সংযুক্ত সর্বনাম)',
        'jenis_bn': 'মুত্তাসিল (সংযুক্ত)',
        'desc_ms': '...-nya / dia (1 orang lelaki, bersambung)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'desc_fr': '...-son / sa / lui (3e personne singulier masculin, pronom attaché)',
        'jenis_fr': 'Muttashil (Attaché)',
        'desc_de': '...-sein / ihm / ihn (3. Person Singular Maskulinum, verbundenes Pronomen)',
        'jenis_de': 'Muttashil (Verbunden)',
        'desc_ur': '...-اس کا / اسے (ایک مرد، ضمیر متصل)',
        'jenis_ur': 'متصل (جڑا ہوا)',
        'desc_hi': '...-उसका / उसे (१ पुरुष, संयुक्त सर्वनाम)',
        'jenis_hi': 'मुत्तसिल (संयुक्त)',
        'jenis_en': 'Muttashil (Attached)'
    },
    '1. Dhamir__1c': {
        'desc_bn': 'কেবল তাকেই / শুধুমাত্র তার কাছেই (পৃথক কর্মকারক ১ পুরুষ)',
        'jenis_bn': 'মুনফাসিল মানসুব (পৃথক কর্মকারক)',
        'desc_ms': 'Hanya kepada-Nya / dia (Objek terpisah 1 lelaki)',
        'jenis_ms': 'Munfashil Manshub',
        'desc_fr': 'À lui seul (Pronom objet détaché, 3e pers. masc.)',
        'jenis_fr': 'Munfashil Manshoub',
        'desc_de': 'Ihm allein (Getrenntes Objektpronomen, 3. Pers. mask.)',
        'jenis_de': 'Munfashil Manshub',
        'desc_ur': 'صرف اسی کو (مفعولی ضمیر منفصل ۱ مرد)',
        'jenis_ur': 'منفصل منصوب',
        'desc_hi': 'केवल उसी को (अलग कर्म सर्वनाम १ पुरुष)',
        'jenis_hi': 'मुन्फ़सिल मंसूब',
        'jenis_en': 'Munfashil Manshub (Detached Object)'
    },
    '1. Dhamir__2a': {
        'desc_bn': 'তারা দুজন (২ জন পুরুষ/নারী, পৃথক সর্বনাম)',
        'jenis_bn': 'মুনফাসিল (পৃথক)',
        'desc_ms': 'Mereka berdua (2 orang L/P terpisah)',
        'jenis_ms': 'Munfashil (Terpisah)',
        'desc_fr': 'Eux deux / Elles deux (3e personne duel, pronom détaché)',
        'jenis_fr': 'Munfashil (Détaché)',
        'desc_de': 'Sie beide (3. Person Dual, getrenntes Pronomen)',
        'jenis_de': 'Munfashil (Getrennt)',
        'desc_ur': 'وہ دونوں (۲ مرد یا عورتیں، ضمیر منفصل)',
        'jenis_ur': 'منفصل (علیحدہ)',
        'desc_hi': 'वे दोनों (२ पुरुष/स्त्री, अलग सर्वनाम)',
        'jenis_hi': 'मुन्फ़सिल (अलग)',
        'jenis_en': 'Munfashil (Detached)'
    },
    '1. Dhamir__2b': {
        'desc_bn': '...-তাদের দুজনের (২ জন পুরুষ/নারী, সংযুক্ত সর্বনাম)',
        'jenis_bn': 'মুত্তাসিল (সংযুক্ত)',
        'desc_ms': '...-mereka berdua (2 orang L/P bersambung)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'desc_fr': '...-leur / eux deux (3e personne duel, pronom attaché)',
        'jenis_fr': 'Muttashil (Attaché)',
        'desc_de': '...-ihrer beider (3. Person Dual, verbundenes Pronomen)',
        'jenis_de': 'Muttashil (Verbunden)',
        'desc_ur': '...-ان دونوں کا (۲ مرد یا عورتیں، ضمیر متصل)',
        'jenis_ur': 'متصل (جڑا ہوا)',
        'desc_hi': '...-उन दोनों का (२ पुरुष/स्त्री, संयुक्त सर्वनाम)',
        'jenis_hi': 'मुत्तसिल (संयुक्त)',
        'jenis_en': 'Muttashil (Attached)'
    },
    '1. Dhamir__3a': {
        'desc_bn': 'তারা (বহু পুরুষ, পৃথক সর্বনাম)',
        'jenis_bn': 'মুনফাসিল (পৃথক)',
        'desc_ms': 'Mereka (ramai lelaki terpisah)',
        'jenis_ms': 'Munfashil (Terpisah)',
        'desc_fr': 'Ils / Eux (3e personne pluriel masculin, pronom détaché)',
        'jenis_fr': 'Munfashil (Détaché)',
        'desc_de': 'Sie (3. Person Plural Maskulinum, getrenntes Pronomen)',
        'jenis_de': 'Munfashil (Getrennt)',
        'desc_ur': 'وہ سب (جمع مذکر، ضمیر منفصل)',
        'jenis_ur': 'منفصل (علیحدہ)',
        'desc_hi': 'वे सब (बहुवचन पुरुष, अलग सर्वनाम)',
        'jenis_hi': 'मुन्फ़सिल (अलग)',
        'jenis_en': 'Munfashil (Detached)'
    },
    '1. Dhamir__3b': {
        'desc_bn': '...-তাদের (বহু পুরুষ, সংযুক্ত সর্বনাম)',
        'jenis_bn': 'মুত্তাসিল (সংযুক্ত)',
        'desc_ms': '...-mereka (ramai lelaki bersambung)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'desc_fr': '...-leur / leurs / eux (3e personne pluriel masculin, pronom attaché)',
        'jenis_fr': 'Muttashil (Attaché)',
        'desc_de': '...-ihr / ihnen / sie (3. Person Plural Maskulinum, verbundenes Pronomen)',
        'jenis_de': 'Muttashil (Verbunden)',
        'desc_ur': '...-ان سب کا / انہیں (جمع مذکر، ضمیر متصل)',
        'jenis_ur': 'متصل (جڑا ہوا)',
        'desc_hi': '...-उनका / उन्हें (बहुवचन पुरुष, संयुक्त सर्वनाम)',
        'jenis_hi': 'मुत्तसिल (संयुक्त)',
        'jenis_en': 'Muttashil (Attached)'
    },
    '1. Dhamir__3c': {
        'desc_bn': 'কেবল তাদেরকেই (পৃথক কর্মকারক বহু পুরুষ)',
        'jenis_bn': 'মুনফাসিল মানসুব (পৃথক কর্মকারক)',
        'desc_ms': 'Hanya kepada mereka (Objek terpisah jamak lelaki)',
        'jenis_ms': 'Munfashil Manshub',
        'desc_fr': 'À eux seuls (Pronom objet détaché, 3e pers. plur. masc.)',
        'jenis_fr': 'Munfashil Manshoub',
        'desc_de': 'Ihnen allein (Getrenntes Objektpronomen, 3. Pers. plur. mask.)',
        'jenis_de': 'Munfashil Manshub',
        'desc_ur': 'صرف انہی کو (مفعولی ضمیر منفصل جمع مذکر)',
        'jenis_ur': 'منفصل منصوب',
        'desc_hi': 'केवल उन्हीं को (अलग कर्म सर्वनाम बहुवचन पुरुष)',
        'jenis_hi': 'मुन्फ़सिल मंसूब',
        'jenis_en': 'Munfashil Manshub (Detached Object)'
    },
    '1. Dhamir__4a': {
        'desc_bn': 'তিনি / সে (১ জন নারী, পৃথক সর্বনাম)',
        'jenis_bn': 'মুনফাসিল (পৃথক)',
        'desc_ms': 'Dia (1 orang perempuan terpisah)',
        'jenis_ms': 'Munfashil (Terpisah)',
        'desc_fr': 'Elle (3e personne singulier féminin, pronom détaché)',
        'jenis_fr': 'Munfashil (Détaché)',
        'desc_de': 'Sie (3. Person Singular Femininum, getrenntes Pronomen)',
        'jenis_de': 'Munfashil (Getrennt)',
        'desc_ur': 'وہ (ایک عورت، ضمیر منفصل)',
        'jenis_ur': 'منفصل (علیحدہ)',
        'desc_hi': 'वह (१ स्त्री, अलग सर्वनाम)',
        'jenis_hi': 'मुन्फ़सिल (अलग)',
        'jenis_en': 'Munfashil (Detached)'
    },
    '1. Dhamir__4b': {
        'desc_bn': '...-তার / তাকে (১ জন নারী, সংযুক্ত সর্বনাম)',
        'jenis_bn': 'মুত্তাসিল (সংযুক্ত)',
        'desc_ms': '...-nya (1 orang perempuan bersambung)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'desc_fr': '...-sa / son / elle (3e personne singulier féminin, pronom attaché)',
        'jenis_fr': 'Muttashil (Attaché)',
        'desc_de': '...-ihr / sie (3. Person Singular Femininum, verbundenes Pronomen)',
        'jenis_de': 'Muttashil (Verbunden)',
        'desc_ur': '...-اس کا / اسے (ایک عورت، ضمیر متصل)',
        'jenis_ur': 'متصل (جڑا ہوا)',
        'desc_hi': '...-उसका / उसे (१ स्त्री, संयुक्त सर्वनाम)',
        'jenis_hi': 'मुत्तसिल (संयुक्त)',
        'jenis_en': 'Muttashil (Attached)'
    },
    '1. Dhamir__5a': {
        'desc_bn': 'তারা (বহু নারী, পৃথক সর্বনাম)',
        'jenis_bn': 'মুনফাসিল (পৃথক)',
        'desc_ms': 'Mereka (ramai perempuan terpisah)',
        'jenis_ms': 'Munfashil (Terpisah)',
        'desc_fr': 'Elles (3e personne pluriel féminin, pronom détaché)',
        'jenis_fr': 'Munfashil (Détaché)',
        'desc_de': 'Sie (3. Person Plural Femininum, getrenntes Pronomen)',
        'jenis_de': 'Munfashil (Getrennt)',
        'desc_ur': 'وہ سب (جمع مؤنث، ضمیر منفصل)',
        'jenis_ur': 'منفصل (علیحدہ)',
        'desc_hi': 'वे सब (बहुवचन स्त्री, अलग सर्वनाम)',
        'jenis_hi': 'मुन्फ़सिल (अलग)',
        'jenis_en': 'Munfashil (Detached)'
    },
    '1. Dhamir__5b': {
        'desc_bn': '...-তাদের (বহু নারী, সংযুক্ত সর্বনাম)',
        'jenis_bn': 'মুত্তাসিল (সংযুক্ত)',
        'desc_ms': '...-mereka (ramai perempuan bersambung)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'desc_fr': '...-leur / leurs / elles (3e personne pluriel féminin, pronom attaché)',
        'jenis_fr': 'Muttashil (Attaché)',
        'desc_de': '...-ihr / ihnen / sie (3. Person Plural Femininum, verbundenes Pronomen)',
        'jenis_de': 'Muttashil (Verbunden)',
        'desc_ur': '...-ان سب عورتوں کا (جمع مؤنث، ضمیر متصل)',
        'jenis_ur': 'متصل (جڑا ہوا)',
        'desc_hi': '...-उन सब का (बहुवचन स्त्री, संयुक्त सर्वनाम)',
        'jenis_hi': 'मुत्तसिल (संयुक्त)',
        'jenis_en': 'Muttashil (Attached)'
    },
    '1. Dhamir__6a': {
        'desc_bn': 'তুমি / আপনি (১ জন পুরুষ, পৃথক সর্বনাম)',
        'jenis_bn': 'মুনফাসিল (পৃথক)',
        'desc_ms': 'Kamu / Engkau (1 orang lelaki terpisah)',
        'jenis_ms': 'Munfashil (Terpisah)',
        'desc_fr': 'Tu / Toi (2e personne singulier masculin, pronom détaché)',
        'jenis_fr': 'Munfashil (Détaché)',
        'desc_de': 'Du (2. Person Singular Maskulinum, getrenntes Pronomen)',
        'jenis_de': 'Munfashil (Getrennt)',
        'desc_ur': 'تو / آپ (ایک مرد، ضمیر منفصل)',
        'jenis_ur': 'منفصل (علیحدہ)',
        'desc_hi': 'तू / आप (१ पुरुष, अलग सर्वनाम)',
        'jenis_hi': 'मुन्फ़सिल (अलग)',
        'jenis_en': 'Munfashil (Detached)'
    },
    '1. Dhamir__6b': {
        'desc_bn': '...-তোমার / আপনাকে (১ জন পুরুষ, সংযুক্ত সর্বনাম)',
        'jenis_bn': 'মুত্তাসিল (সংযুক্ত)',
        'desc_ms': '...-mu / engkau (1 orang lelaki bersambung)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'desc_fr': '...-ton / ta / toi (2e personne singulier masculin, pronom attaché)',
        'jenis_fr': 'Muttashil (Attaché)',
        'desc_de': '...-dein / dir / dich (2. Person Singular Maskulinum, verbundenes Pronomen)',
        'jenis_de': 'Muttashil (Verbunden)',
        'desc_ur': '...-تیرا / تجھے (ایک مرد، ضمیر متصل)',
        'jenis_ur': 'متصل (جڑا ہوا)',
        'desc_hi': '...-तेरा / तुझे (१ पुरुष, संयुक्त सर्वनाम)',
        'jenis_hi': 'मुत्तसिल (संयुक्त)',
        'jenis_en': 'Muttashil (Attached)'
    },
    '1. Dhamir__6c': {
        'desc_bn': 'কেবল তোমাকেই / শুধুমাত্র আপনারই (পৃথক কর্মকারক ১ পুরুষ)',
        'jenis_bn': 'মুনফাসিল মানসুব (পৃথক কর্মকারক)',
        'desc_ms': 'Hanya kepada-Mu / engkau (Objek terpisah 1 lelaki)',
        'jenis_ms': 'Munfashil Manshub',
        'desc_fr': 'À Toi seul (Pronom objet détaché, 2e pers. masc.)',
        'jenis_fr': 'Munfashil Manshoub',
        'desc_de': 'Dir allein (Getrenntes Objektpronomen, 2. Pers. mask.)',
        'jenis_de': 'Munfashil Manshub',
        'desc_ur': 'صرف تجھی کو / آپ ہی کو (مفعولی ضمیر منفصل)',
        'jenis_ur': 'منفصل منصوب',
        'desc_hi': 'केवल तुम्हीं को / केवल आप ही को (अलग कर्म सर्वनाम)',
        'jenis_hi': 'मुन्फ़सिल मंसूब',
        'jenis_en': 'Munfashil Manshub (Detached Object)'
    },
    '1. Dhamir__7a': {
        'desc_bn': 'তোমরা দুজন (২ জন পুরুষ/নারী, পৃথক সর্বনাম)',
        'jenis_bn': 'মুনফাসিল (পৃথক)',
        'desc_ms': 'Kamu berdua (2 orang L/P terpisah)',
        'jenis_ms': 'Munfashil (Terpisah)',
        'desc_fr': 'Vous deux (2e personne duel, pronom détaché)',
        'jenis_fr': 'Munfashil (Détaché)',
        'desc_de': 'Ihr beide (2. Person Dual, getrenntes Pronomen)',
        'jenis_de': 'Munfashil (Getrennt)',
        'desc_ur': 'تم دونوں (۲ مرد یا عورتیں، ضمیر منفصل)',
        'jenis_ur': 'منفصل (علیحدہ)',
        'desc_hi': 'तुम दोनों (२ पुरुष/स्त्री, अलग सर्वनाम)',
        'jenis_hi': 'मुन्फ़सिल (अलग)',
        'jenis_en': 'Munfashil (Detached)'
    },
    '1. Dhamir__7b': {
        'desc_bn': '...-তোমাদের দুজনের (২ জন পুরুষ/নারী, সংযুক্ত সর্বনাম)',
        'jenis_bn': 'মুত্তাসিল (সংযুক্ত)',
        'desc_ms': '...-kamu berdua (2 orang L/P bersambung)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'desc_fr': '...-votre / vous deux (2e personne duel, pronom attaché)',
        'jenis_fr': 'Muttashil (Attaché)',
        'desc_de': '...-euer beider (2. Person Dual, verbundenes Pronomen)',
        'jenis_de': 'Muttashil (Verbunden)',
        'desc_ur': '...-تم دونوں کا (۲ مرد یا عورتیں، ضمیر متصل)',
        'jenis_ur': 'متصل (جڑا ہوا)',
        'desc_hi': '...-तुम दोनों का (२ पुरुष/स्त्री, संयुक्त सर्वनाम)',
        'jenis_hi': 'मुत्तसिल (संयुक्त)',
        'jenis_en': 'Muttashil (Attached)'
    },
    '1. Dhamir__8a': {
        'desc_bn': 'তোমরা / আপনারা (বহু পুরুষ, পৃথক সর্বনাম)',
        'jenis_bn': 'মুনফাসিল (পৃথক)',
        'desc_ms': 'Kalian / Kamu semua (ramai lelaki terpisah)',
        'jenis_ms': 'Munfashil (Terpisah)',
        'desc_fr': 'Vous (2e personne pluriel masculin, pronom détaché)',
        'jenis_fr': 'Munfashil (Détaché)',
        'desc_de': 'Ihr (2. Person Plural Maskulinum, getrenntes Pronomen)',
        'jenis_de': 'Munfashil (Getrennt)',
        'desc_ur': 'تم سب / آپ لوگ (جمع مذکر، ضمیر منفصل)',
        'jenis_ur': 'منفصل (علیحدہ)',
        'desc_hi': 'तुम सब / आप लोग (बहुवचन पुरुष, अलग सर्वनाम)',
        'jenis_hi': 'मुन्फ़सिल (अलग)',
        'jenis_en': 'Munfashil (Detached)'
    },
    '1. Dhamir__8b': {
        'desc_bn': '...-তোমাদের / আপনাদের (বহু পুরুষ, সংযুক্ত সর্বনাম)',
        'jenis_bn': 'মুত্তাসিল (সংযুক্ত)',
        'desc_ms': '...-kalian (ramai lelaki bersambung)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'desc_fr': '...-votre / vos / vous (2e personne pluriel masculin, pronom attaché)',
        'jenis_fr': 'Muttashil (Attaché)',
        'desc_de': '...-euer / euch (2. Person Plural Maskulinum, verbundenes Pronomen)',
        'jenis_de': 'Muttashil (Verbunden)',
        'desc_ur': '...-تم سب کا / آپ لوگوں کا (جمع مذکر، ضمیر متصل)',
        'jenis_ur': 'متصل (جڑا ہوا)',
        'desc_hi': '...-तुम सबका / आपका (बहुवचन पुरुष, संयुक्त सर्वनाम)',
        'jenis_hi': 'मुत्तसिल (संयुक्त)',
        'jenis_en': 'Muttashil (Attached)'
    },
    '1. Dhamir__8c': {
        'desc_bn': 'কেবল তোমাদেরকেই (পৃথক কর্মকারক বহু পুরুষ)',
        'jenis_bn': 'মুনফাসিল মানসুব (পৃথক কর্মকারক)',
        'desc_ms': 'Hanya kepada kalian (Objek terpisah jamak lelaki)',
        'jenis_ms': 'Munfashil Manshub',
        'desc_fr': 'À vous seuls (Pronom objet détaché, 2e pers. plur. masc.)',
        'jenis_fr': 'Munfashil Manshoub',
        'desc_de': 'Euch allein (Getrenntes Objektpronomen, 2. Pers. plur. mask.)',
        'jenis_de': 'Munfashil Manshub',
        'desc_ur': 'صرف تم ہی لوگوں کو (مفعولی ضمیر منفصل جمع مذکر)',
        'jenis_ur': 'منفصل منصوب',
        'desc_hi': 'केवल तुम ही लोगों को (अलग कर्म सर्वनाम बहुवचन पुरुष)',
        'jenis_hi': 'मुन्फ़सिल मंसूब',
        'jenis_en': 'Munfashil Manshub (Detached Object)'
    },
    '1. Dhamir__9b': {
        'desc_bn': '...-তোমার (১ জন নারী, সংযুক্ত সর্বনাম)',
        'jenis_bn': 'মুত্তাসিল (সংযুক্ত)',
        'desc_ms': '...-mu (1 orang perempuan bersambung)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'desc_fr': '...-ton / ta / toi (2e personne singulier féminin, pronom attaché)',
        'jenis_fr': 'Muttashil (Attaché)',
        'desc_de': '...-dein / dir / dich (2. Person Singular Femininum, verbundenes Pronomen)',
        'jenis_de': 'Muttashil (Verbunden)',
        'desc_ur': '...-تیرا (ایک عورت، ضمیر متصل)',
        'jenis_ur': 'متصل (جڑا ہوا)',
        'desc_hi': '...-तेरा (१ स्त्री, संयुक्त सर्वनाम)',
        'jenis_hi': 'मुत्तसिल (संयुक्त)',
        'jenis_en': 'Muttashil (Attached)'
    },
    '1. Dhamir__11a': {
        'desc_bn': 'আমি (১ জন পুরুষ/নারী, পৃথক সর্বনাম)',
        'jenis_bn': 'মুনফাসিল (পৃথক)',
        'desc_ms': 'Saya / Aku (1 orang L/P terpisah)',
        'jenis_ms': 'Munfashil (Terpisah)',
        'desc_fr': 'Je / Moi (1re personne singulier, pronom détaché)',
        'jenis_fr': 'Munfashil (Détaché)',
        'desc_de': 'Ich (1. Person Singular, getrenntes Pronomen)',
        'jenis_de': 'Munfashil (Getrennt)',
        'desc_ur': 'میں (متکلم واحد، ضمیر منفصل)',
        'jenis_ur': 'منفصل (علیحدہ)',
        'desc_hi': 'मैं (उत्तम पुरुष एकवचन, अलग सर्वनाम)',
        'jenis_hi': 'मुन्फ़सिल (अलग)',
        'jenis_en': 'Munfashil (Detached)'
    },
    '1. Dhamir__11b': {
        'desc_bn': '...-আমার / আমাকে (১ জন পুরুষ/নারী, সংযুক্ত সর্বনাম)',
        'jenis_bn': 'মুত্তাসিল (সংযুক্ত)',
        'desc_ms': '...-ku / saya (1 orang L/P bersambung)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'desc_fr': '...-mon / ma / me / moi (1re personne singulier, pronom attaché)',
        'jenis_fr': 'Muttashil (Attaché)',
        'desc_de': '...-mein / mir / mich (1. Person Singular, verbundenes Pronomen)',
        'jenis_de': 'Muttashil (Verbunden)',
        'desc_ur': '...-میرا / مجھے (متکلم واحد، ضمیر متصل)',
        'jenis_ur': 'متصل (جڑا ہوا)',
        'desc_hi': '...-मेरा / मुझे (उत्तम पुरुष एकवचन, संयुक्त सर्वनाम)',
        'jenis_hi': 'मुत्तसिल (संयुक्त)',
        'jenis_en': 'Muttashil (Attached)'
    },
    '1. Dhamir__11c': {
        'desc_bn': 'কেবল আমাকেই / শুধুমাত্র আমারই (পৃথক কর্মকারক ১ পুরুষ/নারী)',
        'jenis_bn': 'মুনফাসিল মানসুব (পৃথক কর্মকারক)',
        'desc_ms': 'Hanya kepada-Ku / aku (Objek terpisah 1 L/P)',
        'jenis_ms': 'Munfashil Manshub',
        'desc_fr': 'À Moi seul (Pronom objet détaché, 1re pers. sing.)',
        'jenis_fr': 'Munfashil Manshoub',
        'desc_de': 'Mir allein (Getrenntes Objektpronomen, 1. Pers. sing.)',
        'jenis_de': 'Munfashil Manshub',
        'desc_ur': 'صرف مجھی کو (مفعولی ضمیر منفصل متکلم)',
        'jenis_ur': 'منفصل منصوب',
        'desc_hi': 'केवल मुझ ही को (अलग कर्म सर्वनाम उत्तम पुरुष)',
        'jenis_hi': 'मुन्फ़सिल मंसूब',
        'jenis_en': 'Munfashil Manshub (Detached Object)'
    },
    '1. Dhamir__12a': {
        'desc_bn': 'আমরা (বহুবচন পুরুষ/নারী, পৃথক সর্বনাম)',
        'jenis_bn': 'মুনফাসিল (পৃথক)',
        'desc_ms': 'Kami / Kita (jamak L/P terpisah)',
        'jenis_ms': 'Munfashil (Terpisah)',
        'desc_fr': 'Nous (1re personne pluriel, pronom détaché)',
        'jenis_fr': 'Munfashil (Détaché)',
        'desc_de': 'Wir (1. Person Plural, getrenntes Pronomen)',
        'jenis_de': 'Munfashil (Getrennt)',
        'desc_ur': 'ہم / ہم سب (متکلم مع الغیر، ضمیر منفصل)',
        'jenis_ur': 'منفصل (علیحدہ)',
        'desc_hi': 'हम / हम सब (उत्तम पुरुष बहुवचन, अलग सर्वनाम)',
        'jenis_hi': 'मुन्फ़सिल (अलग)',
        'jenis_en': 'Munfashil (Detached)'
    },
    '1. Dhamir__12b': {
        'desc_bn': '...-আমাদের (বহুবচন পুরুষ/নারী, সংযুক্ত সর্বনাম)',
        'jenis_bn': 'মুত্তাসিল (সংযুক্ত)',
        'desc_ms': '...-kami / kita (jamak L/P bersambung)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'desc_fr': '...-notre / nos / nous (1re personne pluriel, pronom attaché)',
        'jenis_fr': 'Muttashil (Attaché)',
        'desc_de': '...-unser / uns (1. Person Plural, verbundenes Pronomen)',
        'jenis_de': 'Muttashil (Verbunden)',
        'desc_ur': '...-ہمارا / ہمیں (متکلم مع الغیر، ضمیر متصل)',
        'jenis_ur': 'متصل (جڑا ہوا)',
        'desc_hi': '...-हमारा / हमें (उत्तम पुरुष बहुवचन, संयुक्त सर्वनाम)',
        'jenis_hi': 'मुत्तसिल (संयुक्त)',
        'jenis_en': 'Muttashil (Attached)'
    },
    '1. Dhamir__12c': {
        'desc_bn': 'কেবল আমাদেরকেই (পৃথক কর্মকারক বহুবচন)',
        'jenis_bn': 'মুনফাসিল মানসুব (পৃথক কর্মকারক)',
        'desc_ms': 'Hanya kepada kami / kita (Objek terpisah jamak)',
        'jenis_ms': 'Munfashil Manshub',
        'desc_fr': 'À nous seuls (Pronom objet détaché, 1re pers. plur.)',
        'jenis_fr': 'Munfashil Manshoub',
        'desc_de': 'Uns allein (Getrenntes Objektpronomen, 1. Pers. plur.)',
        'jenis_de': 'Munfashil Manshub',
        'desc_ur': 'صرف ہم ہی کو (مفعولی ضمیر منفصل متکلم مع الغیر)',
        'jenis_ur': 'منفصل منصوب',
        'desc_hi': 'केवल हम ही को (अलग कर्म सर्वनाम बहुवचन)',
        'jenis_hi': 'मुन्फ़सिल मंसूब',
        'jenis_en': 'Munfashil Manshub (Detached Object)'
    },
    '2. Mawshul__1': {
        'desc_bn': 'যা কিছু / যা (অচেতন / অপ্রাণিবাচক সম্বন্ধবাচক সর্বনাম)',
        'jenis_bn': 'মাওসুল মুশতাকার (সাধারণ সম্বন্ধবাচক)',
        'desc_ms': 'Apa yang / Sesuatu yang (Bukan Manusia / Ghairil Aqil)',
        'jenis_ms': 'Mawshul Musytarak',
        'desc_fr': 'Ce que / Ce qui (Pronom relatif pour non-humains)',
        'jenis_fr': 'Mawshul Mushtarak (Relatif Commun)',
        'desc_de': 'Was / Das, was (Relativpronomen für Unbelebtes)',
        'jenis_de': 'Mawshul Mushtarak (Gemeinsames Relativpronomen)',
        'desc_ur': 'جو کچھ / وہ جو (غیر ذوی العقول کے لیے اسم موصول)',
        'jenis_ur': 'اسم موصول مشترک',
        'desc_hi': 'जो कुछ / जो कि (अचेतन के लिए संबंधवाचक सर्वनाम)',
        'jenis_hi': 'मौसूल मुश्तरक',
        'jenis_en': 'Mawshul Musytarak (Common Relative)'
    },
    '2. Mawshul__2': {
        'desc_bn': 'যারা / যে সকল ব্যক্তি (বহুবচন পুরুষ সম্বন্ধবাচক সর্বনাম)',
        'jenis_bn': 'মাওসুল খাস (নির্দিষ্ট সম্বন্ধবাচক)',
        'desc_ms': 'Orang-orang yang (Jamak Lelaki)',
        'jenis_ms': 'Mawshul Khash',
        'desc_fr': 'Ceux qui (Pronom relatif pluriel masculin)',
        'jenis_fr': 'Mawshul Khas (Relatif Spécifique)',
        'desc_de': 'Diejenigen, die (Relativpronomen Plural Maskulinum)',
        'jenis_de': 'Mawshul Khas (Spezifisches Relativpronomen)',
        'desc_ur': 'وہ لوگ جو (جمع مذکر کے لیے اسم موصول)',
        'jenis_ur': 'اسم موصول خاص',
        'desc_hi': 'जो लोग / वे जो (बहुवचन पुरुष संबंधवाचक सर्वनाम)',
        'jenis_hi': 'मौसूल ख़ास',
        'jenis_en': 'Mawshul Khash (Specific Relative)'
    },
    '2. Mawshul__3': {
        'desc_bn': 'যে / যারা / যে ব্যক্তি (সচেতন / মানববাচক সম্বন্ধবাচক সর্বনাম)',
        'jenis_bn': 'মাওসুল মুশতাকার (সাধারণ সম্বন্ধবাচক)',
        'desc_ms': 'Siapa yang / Orang yang (Berakal / Manusia)',
        'jenis_ms': 'Mawshul Musytarak',
        'desc_fr': 'Quiconque / Celui qui (Pronom relatif pour êtres doués de raison)',
        'jenis_fr': 'Mawshul Mushtarak (Relatif Commun)',
        'desc_de': 'Wer / Derjenige, der (Relativpronomen für vernunftbegabte Wesen)',
        'jenis_de': 'Mawshul Mushtarak (Gemeinsames Relativpronomen)',
        'desc_ur': 'جو کوئی / وہ شخص جو (ذوی العقول کے لیے اسم موصول)',
        'jenis_ur': 'اسم موصول مشترک',
        'desc_hi': 'जो कोई / वह जो (सचेतन के लिए संबंधवाचक सर्वनाम)',
        'jenis_hi': 'मौसूल मुश्तरक',
        'jenis_en': 'Mawshul Musytarak (Common Relative)'
    },
    '2. Mawshul__4': {
        'desc_bn': 'যিনি / যে ব্যক্তি (১ জন পুরুষ সম্বন্ধবাচক সর্বনাম)',
        'jenis_bn': 'মাওসুল খাস (নির্দিষ্ট সম্বন্ধবাচক)',
        'desc_ms': 'Orang yang / Sesuatu yang (1 orang Lelaki)',
        'jenis_ms': 'Mawshul Khash',
        'desc_fr': 'Celui qui / Lequel (Pronom relatif singulier masculin)',
        'jenis_fr': 'Mawshul Khas (Relatif Spécifique)',
        'desc_de': 'Derjenige, welcher (Relativpronomen Singular Maskulinum)',
        'jenis_de': 'Mawshul Khas (Spezifisches Relativpronomen)',
        'desc_ur': 'وہ جو / وہ شخص جو (واحد مذکر کے لیے اسم موصول)',
        'jenis_ur': 'اسم موصول خاص',
        'desc_hi': 'वह जो / जो व्यक्ति (१ पुरुष संबंधवाचक सर्वनाम)',
        'jenis_hi': 'मौसूल ख़ास',
        'jenis_en': 'Mawshul Khash (Specific Relative)'
    },
    '2. Mawshul__5': {
        'desc_bn': 'যে কোনোটি / যে কেউ (রূপান্তরযোগ্য সম্বন্ধবাচক সর্বনাম)',
        'jenis_bn': 'মাওসুল মুবহাম (অনির্দিষ্ট সম্বন্ধবাচক)',
        'desc_ms': 'Yang mana saja / siapa saja (Mu\'rab)',
        'jenis_ms': 'Mawshul Mubham',
        'desc_fr': 'Lequel / N\'importe lequel (Pronom relatif déclinable)',
        'jenis_fr': 'Mawshul Moubham',
        'desc_de': 'Welcher auch immer (Deklinierbares Relativpronomen)',
        'jenis_de': 'Mawshul Mubham',
        'desc_ur': 'جو کوئی بھی / جو سا بھی (معرب اسم موصول)',
        'jenis_ur': 'اسم موصول مبہم',
        'desc_hi': 'जो कोई भी / जो सा भी (संबंधवाचक सर्वनाम)',
        'jenis_hi': 'मौसूल मुबहम',
        'jenis_en': 'Mawshul Mubham (Vague Relative)'
    },
    '2. Mawshul__6': {
        'desc_bn': 'যিনি / যে নারী / যে বস্তু (১ জন নারী সম্বন্ধবাচক সর্বনাম)',
        'jenis_bn': 'মাওসুল খাস (নির্দিষ্ট সম্বন্ধবাচক)',
        'desc_ms': 'Orang yang / Sesuatu yang (1 orang Perempuan)',
        'jenis_ms': 'Mawshul Khash',
        'desc_fr': 'Celle qui / Laquelle (Pronom relatif singulier féminin)',
        'jenis_fr': 'Mawshul Khas (Relatif Spécifique)',
        'desc_de': 'Diejenige, welche (Relativpronomen Singular Femininum)',
        'jenis_de': 'Mawshul Khas (Spezifisches Relativpronomen)',
        'desc_ur': 'وہ عورت جو (واحد مؤنث کے لیے اسم موصول)',
        'jenis_ur': 'اسم موصول خاص',
        'desc_hi': 'वह स्त्री जो (१ स्त्री संबंधवाचक सर्वनाम)',
        'jenis_hi': 'मौसूल ख़ास',
        'jenis_en': 'Mawshul Khash (Specific Relative)'
    },
    '2. Mawshul__7': {
        'desc_bn': 'যে সকল নারী (বহুবচন নারী সম্বন্ধবাচক সর্বনাম)',
        'jenis_bn': 'মাওসুল খাস (নির্দিষ্ট সম্বন্ধবাচক)',
        'desc_ms': 'Wanita-wanita yang (Jamak Perempuan)',
        'jenis_ms': 'Mawshul Khash',
        'desc_fr': 'Celles qui (Pronom relatif pluriel féminin)',
        'jenis_fr': 'Mawshul Khas (Relatif Spécifique)',
        'desc_de': 'Diejenigen Frauen, die (Relativpronomen Plural Femininum)',
        'jenis_de': 'Mawshul Khas (Spezifisches Relativpronomen)',
        'desc_ur': 'وہ عورتیں جو (جمع مؤنث کے لیے اسم موصول)',
        'jenis_ur': 'اسم موصول خاص',
        'desc_hi': 'वे स्त्रियां जो (बहुवचन स्त्री संबंधवाचक सर्वनाम)',
        'jenis_hi': 'मौसूल ख़ास',
        'jenis_en': 'Mawshul Khash (Specific Relative)'
    },
    '2. Mawshul__8': {
        'desc_bn': 'যে সকল নারী (বহুবচন নারী সম্বন্ধবাচক সর্বনাম)',
        'jenis_bn': 'মাওসুল খাস (নির্দিষ্ট সম্বন্ধবাচক)',
        'desc_ms': 'Wanita-wanita yang (Jamak Perempuan)',
        'jenis_ms': 'Mawshul Khash',
        'desc_fr': 'Celles qui (Pronom relatif pluriel féminin)',
        'jenis_fr': 'Mawshul Khas (Relatif Spécifique)',
        'desc_de': 'Diejenigen Frauen, die (Relativpronomen Plural Femininum)',
        'jenis_de': 'Mawshul Khas (Spezifisches Relativpronomen)',
        'desc_ur': 'وہ عورتیں جو (جمع مؤنث کے لیے اسم موصول)',
        'jenis_ur': 'اسم موصول خاص',
        'desc_hi': 'वे स्त्रियां जो (बहुवचन स्त्री संबंधवाचक सर्वनाम)',
        'jenis_hi': 'मौसूल ख़ास',
        'jenis_en': 'Mawshul Khash (Specific Relative)'
    },
    '2. Mawshul__9': {
        'desc_bn': 'যে দুজন পুরুষ (দ্বিবচন পুরুষ সম্বন্ধবাচক সর্বনাম)',
        'jenis_bn': 'মাওসুল খাস (নির্দিষ্ট সম্বন্ধবাচক)',
        'desc_ms': 'Dua orang yang (2 Lelaki, Mu\'rab)',
        'jenis_ms': 'Mawshul Khash',
        'desc_fr': 'Les deux hommes qui (Pronom relatif duel masculin)',
        'jenis_fr': 'Mawshul Khas (Relatif Spécifique)',
        'desc_de': 'Die beiden Männer, die (Relativpronomen Dual Maskulinum)',
        'jenis_de': 'Mawshul Khas (Spezifisches Relativpronomen)',
        'desc_ur': 'وہ دونوں مرد جو (تثنیہ مذکر کے لیے اسم موصول)',
        'jenis_ur': 'اسم موصول خاص',
        'desc_hi': 'वे दोनों पुरुष जो (द्विवचन पुरुष संबंधवाचक सर्वनाम)',
        'jenis_hi': 'मौसूल ख़ास',
        'jenis_en': 'Mawshul Khash (Specific Relative)'
    },
    '2. Mawshul__10': {
        'desc_bn': 'যে কোনোটি / যে নারী (স্ত্রীলিঙ্গ সম্বন্ধবাচক সর্বনাম)',
        'jenis_bn': 'মাওসুল মুবহাম (অনির্দিষ্ট সম্বন্ধবাচক)',
        'desc_ms': 'Yang mana saja (Bentuk Perempuan)',
        'jenis_ms': 'Mawshul Mubham',
        'desc_fr': 'Laquelle / N\'importe laquelle (Forme féminine déclinable)',
        'jenis_fr': 'Mawshul Moubham',
        'desc_de': 'Welche auch immer (Feminine Form)',
        'jenis_de': 'Mawshul Mubham',
        'desc_ur': 'جو کوئی بھی عورت (مؤنث اسم موصول)',
        'jenis_ur': 'اسم موصول مبہم',
        'desc_hi': 'जो कोई भी स्त्री (स्त्रीलिंग संबंधवाचक सर्वनाम)',
        'jenis_hi': 'मौसूल मुबहम',
        'jenis_en': 'Mawshul Mubham (Vague Relative)'
    },
    '3. Istifham__1': {
        'desc_bn': 'কী / কী বস্তু (অপ্রাণিবাচক প্রশ্নবোধক শব্দ)',
        'jenis_bn': 'ইসম ইসতিফহাম (প্রশ্নবোধক বিশেষ্য)',
        'desc_ms': 'Apakah / Apa yang (Menanyakan benda / perkara)',
        'jenis_ms': 'Isim Istifham',
        'desc_fr': 'Qu\'est-ce que / Quoi (Interrogatif pour choses)',
        'jenis_fr': 'Ism Istifham (Nom Interrogatif)',
        'desc_de': 'Was (Fragewort für Sachen/Angelegenheiten)',
        'jenis_de': 'Ism Istifham (Interrogativpronomen)',
        'desc_ur': 'کیا / کیا چیز (غیر ذوی العقول کے لیے استفہام)',
        'jenis_ur': 'اسم استفہام',
        'desc_hi': 'क्या / क्या चीज़ (अचेतन के लिए प्रश्नवाचक)',
        'jenis_hi': 'इस्म इस्तिफ़हाम',
        'jenis_en': 'Ism Istifham (Interrogative Noun)'
    },
    '3. Istifham__2': {
        'desc_bn': 'কেমন করে / কীভাবে (অবস্থা ও পদ্ধতি জানার প্রশ্নবোধক শব্দ)',
        'jenis_bn': 'ইসম ইসতিফহাম (প্রশ্নবোধক বিশেষ্য)',
        'desc_ms': 'Bagaimana (Menanyakan keadaan / cara)',
        'jenis_ms': 'Isim Istifham',
        'desc_fr': 'Comment (Interrogatif sur l\'état ou la manière)',
        'jenis_fr': 'Ism Istifham (Nom Interrogatif)',
        'desc_de': 'Wie (Fragewort nach Zustand oder Art und Weise)',
        'jenis_de': 'Ism Istifham (Interrogativpronomen)',
        'desc_ur': 'کیسے / کس طرح (حالت یا طریقے کا استفہام)',
        'jenis_ur': 'اسم استفہام',
        'desc_hi': 'कैसे / किस प्रकार (स्थिति व रीति का प्रश्नवाचक)',
        'jenis_hi': 'इस्म इस्तिफ़हाम',
        'jenis_en': 'Ism Istifham (Interrogative Noun)'
    },
    '3. Istifham__3': {
        'desc_bn': 'কে / কারা (ব্যক্তি ও সচেতনদের জানার প্রশ্নবোধক শব্দ)',
        'jenis_bn': 'ইসম ইসতিফহাম (প্রশ্নবোধক বিশেষ্য)',
        'desc_ms': 'Siapakah (Menanyakan pelaku / yang berakal)',
        'jenis_ms': 'Isim Istifham',
        'desc_fr': 'Qui (Interrogatif pour êtres doués de raison)',
        'jenis_fr': 'Ism Istifham (Nom Interrogatif)',
        'desc_de': 'Wer (Fragewort für Personen)',
        'jenis_de': 'Ism Istifham (Interrogativpronomen)',
        'desc_ur': 'کون / کس نے (ذوی العقول کے لیے استفہام)',
        'jenis_ur': 'اسم استفہام',
        'desc_hi': 'कौन / किसने (सचेतन के लिए प्रश्नवाचक)',
        'jenis_hi': 'इस्म इस्तिफ़हाम',
        'jenis_en': 'Ism Istifham (Interrogative Noun)'
    },
    '3. Istifham__4': {
        'desc_bn': 'কোনটি / কোনটি সেরা (রূপান্তরযোগ্য প্রশ্নবোধক শব্দ)',
        'jenis_bn': 'ইসম ইসতিফহাম (প্রশ্নবোধক বিশেষ্য)',
        'desc_ms': 'Yang mana / apakah (Kata tanya Mu\'rab)',
        'jenis_ms': 'Isim Istifham',
        'desc_fr': 'Lequel / Quel (Interrogatif déclinable)',
        'jenis_fr': 'Ism Istifham (Nom Interrogatif)',
        'desc_de': 'Welcher / Welches (Deklinierbares Fragewort)',
        'jenis_de': 'Ism Istifham (Interrogativpronomen)',
        'desc_ur': 'کون سا / کون سے (معرب اسم استفہام)',
        'jenis_ur': 'اسم استفہام',
        'desc_hi': 'कौन सा / कौन से (प्रश्नवाचक शब्द)',
        'jenis_hi': 'इस्म इस्तिफ़हाम',
        'jenis_en': 'Ism Istifham (Interrogative Noun)'
    },
    '3. Istifham__5': {
        'desc_bn': 'কীভাবে / কোথা থেকে / কখন (অবস্থা ও উৎসের প্রশ্নবোধক শব্দ)',
        'jenis_bn': 'ইসম ইসতিফহাম (প্রশ্নবোধক বিশেষ্য)',
        'desc_ms': 'Bagaimana / dari manakah / kapan',
        'jenis_ms': 'Isim Istifham',
        'desc_fr': 'Comment / D\'où / Quand (Interrogatif de lieu/manière)',
        'jenis_fr': 'Ism Istifham (Nom Interrogatif)',
        'desc_de': 'Wie / Woher / Wann (Fragewort für Herkunft/Art)',
        'jenis_de': 'Ism Istifham (Interrogativpronomen)',
        'desc_ur': 'کیسے / کہاں سے / کب (استفہام مکان و کیفیت)',
        'jenis_ur': 'اسم استفہام',
        'desc_hi': 'कैसे / कहाँ से / कब (स्थान व रीति का प्रश्नवाचक)',
        'jenis_hi': 'इस्म इस्तिफ़हाम',
        'jenis_en': 'Ism Istifham (Interrogative Noun)'
    },
    '3. Istifham__6': {
        'desc_bn': 'কী এমন বস্তু / কী তা (যৌগিক প্রশ্নবোধক শব্দ)',
        'jenis_bn': 'ইসম ইসতিফহাম (প্রশ্নবোধক বিশেষ্য)',
        'desc_ms': 'Apakah gerangan yang / apa yang (Mā + Dzā)',
        'jenis_ms': 'Isim Istifham',
        'desc_fr': 'Qu\'est-ce donc que (Interrogatif composé)',
        'jenis_fr': 'Ism Istifham (Nom Interrogatif)',
        'desc_de': 'Was ist es, das (Zusammengesetztes Fragewort)',
        'jenis_de': 'Ism Istifham (Interrogativpronomen)',
        'desc_ur': 'کیا چیز ہے جو (مرکب استفہام)',
        'jenis_ur': 'اسم استفہام',
        'desc_hi': 'क्या ऐसी चीज़ है जो (संयुक्त प्रश्नवाचक)',
        'jenis_hi': 'इस्म इस्तिफ़हाम',
        'jenis_en': 'Ism Istifham (Interrogative Noun)'
    },
    '3. Istifham__7': {
        'desc_bn': 'কত / কত সংখ্যক / কত কাল (পরিমাণ ও সময়ের প্রশ্নবোধক শব্দ)',
        'jenis_bn': 'ইসম ইসতিফহাম (প্রশ্নবোধক বিশেষ্য)',
        'desc_ms': 'Berapa banyak / berapa lama (Menanyakan jumlah/waktu)',
        'jenis_ms': 'Isim Istifham',
        'desc_fr': 'Combien / Combien de temps (Interrogatif de quantité/durée)',
        'jenis_fr': 'Ism Istifham (Nom Interrogatif)',
        'desc_de': 'Wie viel / Wie lange (Fragewort für Menge/Zeit)',
        'jenis_de': 'Ism Istifham (Interrogativpronomen)',
        'desc_ur': 'کتنا / کتنے / کتنا عرصہ (استفہام عدد و وقت)',
        'jenis_ur': 'اسم استفہام',
        'desc_hi': 'कितना / कितने / कितने समय (संख्या व समय का प्रश्नवाचक)',
        'jenis_hi': 'इस्म इस्तिफ़हाम',
        'jenis_en': 'Ism Istifham (Interrogative Noun)'
    },
    '3. Istifham__8': {
        'desc_bn': 'কেন / কী কারণে (কারণ জানার প্রশ্নবোধক শব্দ)',
        'jenis_bn': 'ইসম ইসতিফহাম (প্রশ্নবোধক বিশেষ্য)',
        'desc_ms': 'Mengapa / untuk alasan apa (Li + Ma)',
        'jenis_ms': 'Isim Istifham',
        'desc_fr': 'Pourquoi / Pour quelle raison (Li + Ma)',
        'jenis_fr': 'Ism Istifham (Nom Interrogatif)',
        'desc_de': 'Warum / Aus welchem Grund (Li + Ma)',
        'jenis_de': 'Ism Istifham (Interrogativpronomen)',
        'desc_ur': 'کیوں / کس لیے (استفہام سبب)',
        'jenis_ur': 'اسم استفہام',
        'desc_hi': 'क्यों / किस कारण से (कारण का प्रश्नवाचक)',
        'jenis_hi': 'इस्म इस्तिफ़हाम',
        'jenis_en': 'Ism Istifham (Interrogative Noun)'
    },
    '3. Istifham__9': {
        'desc_bn': 'কোথায় / কোন স্থানে (স্থান জানার প্রশ্নবোধক শব্দ)',
        'jenis_bn': 'ইসম ইসতিফহাম (প্রশ্নবোধক বিশেষ্য)',
        'desc_ms': 'Di mana / ke mana (Menanyakan tempat)',
        'jenis_ms': 'Isim Istifham',
        'desc_fr': 'Où / Vers où (Interrogatif de lieu)',
        'jenis_fr': 'Ism Istifham (Nom Interrogatif)',
        'desc_de': 'Wo / Wohin (Fragewort für Ort)',
        'jenis_de': 'Ism Istifham (Interrogativpronomen)',
        'desc_ur': 'کہاں / کدھر (استفہام مکان)',
        'jenis_ur': 'اسم استفہام',
        'desc_hi': 'कहाँ / किधर (स्थान का प्रश्नवाचक)',
        'jenis_hi': 'इस्म इस्तिफ़हाम',
        'jenis_en': 'Ism Istifham (Interrogative Noun)'
    },
    '3. Istifham__10': {
        'desc_bn': 'কখন / কোন্ সময় (সময় জানার প্রশ্নবোধক শব্দ)',
        'jenis_bn': 'ইসম ইসতিফহাম (প্রশ্নবোধক বিশেষ্য)',
        'desc_ms': 'Kapankah (Menanyakan waktu)',
        'jenis_ms': 'Isim Istifham',
        'desc_fr': 'Quand (Interrogatif de temps)',
        'jenis_fr': 'Ism Istifham (Nom Interrogatif)',
        'desc_de': 'Wann (Fragewort für Zeit)',
        'jenis_de': 'Ism Istifham (Interrogativpronomen)',
        'desc_ur': 'کب (استفہام وقت)',
        'jenis_ur': 'اسم استفہام',
        'desc_hi': 'कब (समय का प्रश्नवाचक)',
        'jenis_hi': 'इस्म इस्तिफ़हाम',
        'jenis_en': 'Ism Istifham (Interrogative Noun)'
    },
    '4. Syarath__1': {
        'desc_bn': 'যে কেউ / যে ব্যক্তি (মানববাচক জাযমকারী শর্তমূলক শব্দ)',
        'jenis_bn': 'ইসম শারত জাযিম (জাযমকারী শর্তমূলক শব্দ)',
        'desc_ms': 'Barang siapa yang (Syarat menjazamkan untuk manusia)',
        'jenis_ms': 'Isim Syarat Jazim',
        'desc_fr': 'Quiconque / Celui qui (Conditionnel apocopant pour personnes)',
        'jenis_fr': 'Ism Syarath Jazim (Conditionnel Apocopant)',
        'desc_de': 'Wer auch immer (Apokopierendes Bedingungswort für Personen)',
        'jenis_de': 'Ism Syarath Jazim (Apokopierendes Bedingungswort)',
        'desc_ur': 'جو کوئی بھی (عاقل کے لیے شرط جازمہ)',
        'jenis_ur': 'اسم شرط جازم',
        'desc_hi': 'जो कोई भी (सचेतन के लिए शर्तवाचक शब्द)',
        'jenis_hi': 'इस्म शर्त जाज़िम',
        'jenis_en': 'Ism Syarath Jazim (Apocopating Conditional)'
    },
    '4. Syarath__2': {
        'desc_bn': 'যা কিছুই (অপ্রাণিবাচক জাযমকারী শর্তমূলক শব্দ)',
        'jenis_bn': 'ইসম শারত জাযিম (জাযমকারী শর্তমূলক শব্দ)',
        'desc_ms': 'Apa saja yang (Syarat menjazamkan untuk perkara/benda)',
        'jenis_ms': 'Isim Syarat Jazim',
        'desc_fr': 'Quoi que ce soit / Tout ce que (Conditionnel apocopant pour choses)',
        'jenis_fr': 'Ism Syarath Jazim (Conditionnel Apocopant)',
        'desc_de': 'Was auch immer (Apokopierendes Bedingungswort für Unbelebtes)',
        'jenis_de': 'Ism Syarath Jazim (Apokopierendes Bedingungswort)',
        'desc_ur': 'جو کچھ بھی (غیر عاقل کے لیے شرط جازمہ)',
        'jenis_ur': 'اسم شرط جازم',
        'desc_hi': 'जो कुछ भी (अचेतन के लिए शर्तवाचक शब्द)',
        'jenis_hi': 'इस्म शर्त जाज़िम',
        'jenis_en': 'Ism Syarath Jazim (Apocopating Conditional)'
    },
    '4. Syarath__3': {
        'desc_bn': 'যতবারই / যখনই (সময় ও পুনরাবৃত্তির শর্তমূলক শব্দ)',
        'jenis_bn': 'ইসম শারত গাইরে জাযিম (অ-জাযমকারী শর্তমূলক শব্দ)',
        'desc_ms': 'Setiap kali / tatkala (Syarat waktu / perulangan)',
        'jenis_ms': 'Isim Syarat Ghair Jazim',
        'desc_fr': 'Chaque fois que (Conditionnel temporel non apocopant)',
        'jenis_fr': 'Ism Syarath Ghayr Jazim',
        'desc_de': 'Jedes Mal, wenn (Nicht-apokopierende Zeitbedingung)',
        'jenis_de': 'Ism Syarath Ghayr Jazim',
        'desc_ur': 'جب جب / ہر بار جب (وقت و تکرار کی شرط غیر جازمہ)',
        'jenis_ur': 'اسم شرط غیر جازم',
        'desc_hi': 'हर बार जब / जितनी बार (समय और पुनरावृत्ति की शर्त)',
        'jenis_hi': 'इस्म शर्त ग़ैर जाज़िम',
        'jenis_en': 'Ism Syarath Ghair Jazim (Non-apocopating Conditional)'
    },
    '4. Syarath__4': {
        'desc_bn': 'যে কোনোটিকেই (রূপান্তরযোগ্য শর্তমূলক শব্দ)',
        'jenis_bn': 'ইসম শারত জাযিম (জাযমকারী শর্তমূলক শব্দ)',
        'desc_ms': 'Mana saja yang (Syarat Mu\'rab)',
        'jenis_ms': 'Isim Syarat Jazim',
        'desc_fr': 'Quel que soit celui que (Conditionnel déclinable)',
        'jenis_fr': 'Ism Syarath Jazim',
        'desc_de': 'Welchen auch immer (Deklinierbares Bedingungswort)',
        'jenis_de': 'Ism Syarath Jazim',
        'desc_ur': 'جس کسی کو بھی (معرب اسم شرط)',
        'jenis_ur': 'اسم شرط جازم',
        'desc_hi': 'जिस किसी को भी (शर्तवाचक शब्द)',
        'jenis_hi': 'इस्म शर्त जाज़िम',
        'jenis_en': 'Ism Syarath Jazim (Apocopating Conditional)'
    },
    '4. Syarath__5': {
        'desc_bn': 'যে কোনোটিকেই (দৃঢ়তাজ্ঞাপক শর্তমূলক শব্দ)',
        'jenis_bn': 'ইসম শারত জাযিম (জাযমকারী শর্তমূলক শব্দ)',
        'desc_ms': 'Mana saja (Syarat dengan penegasan Ma Zaidah)',
        'jenis_ms': 'Isim Syarat Jazim',
        'desc_fr': 'N\'importe lequel (Conditionnel avec particule d\'insistance)',
        'jenis_fr': 'Ism Syarath Jazim',
        'desc_de': 'Welchen auch immer (Bedingung mit Verstärkungspartikel)',
        'jenis_de': 'Ism Syarath Jazim',
        'desc_ur': 'جو سا بھی (ما زائدہ کے ساتھ تاکیدی اسم شرط)',
        'jenis_ur': 'اسم شرط جازم',
        'desc_hi': 'जो सा भी (ताकीदी शर्तवाचक शब्द)',
        'jenis_hi': 'इस्म शर्त जाज़िम',
        'jenis_en': 'Ism Syarath Jazim (Apocopating Conditional)'
    },
    '5. Isyarah__1': {
        'desc_bn': 'এই / ঐ (একবচন পুরুষ নির্দেশক সর্বনাম)',
        'jenis_bn': 'ইসম ইশারা (নির্দেশক সর্বনাম)',
        'desc_ms': 'Ini / itu (Kata tunjuk tunggal lelaki)',
        'jenis_ms': 'Isim Isyarat',
        'desc_fr': 'Ceci / Cela (Démonstratif singulier masculin)',
        'jenis_fr': 'Ism Isyarah (Démonstratif)',
        'desc_de': 'Dies / Das / Jener (Demonstrativ Singular Maskulinum)',
        'jenis_de': 'Ism Isyarah (Demonstrativpronomen)',
        'desc_ur': 'یہ / وہ (واحد مذکر، اسم اشارہ)',
        'jenis_ur': 'اسم اشارہ',
        'desc_hi': 'यह / वह (एकवचन पुरुष, संकेतवाचक सर्वनाम)',
        'jenis_hi': 'इस्म इशारा',
        'jenis_en': 'Ism Isyarah (Demonstrative)'
    },
    '5. Isyarah__2': {
        'desc_bn': 'এরা / তারা (বহুবচন নির্দেশক সর্বনাম)',
        'jenis_bn': 'ইসম ইশারা (নির্দেশক সর্বনাম)',
        'desc_ms': 'Mereka ini / itu (Kata tunjuk jamak)',
        'jenis_ms': 'Isim Isyarat',
        'desc_fr': 'Ceux-ci / Ceux-là (Démonstratif pluriel)',
        'jenis_fr': 'Ism Isyarah (Démonstratif)',
        'desc_de': 'Diese / Jene (Demonstrativ Plural)',
        'jenis_de': 'Ism Isyarah (Demonstrativpronomen)',
        'desc_ur': 'یہ سب / وہ سب (جمع، اسم اشارہ)',
        'jenis_ur': 'اسم اشارہ',
        'desc_hi': 'ये सब / वे सब (बहुवचन, संकेतवाचक सर्वनाम)',
        'jenis_hi': 'इस्म इशारा',
        'jenis_en': 'Ism Isyarah (Demonstrative)'
    },
    '5. Isyarah__3': {
        'desc_bn': 'এই / ঐ (একবচন নারী নির্দেশক সর্বনাম)',
        'jenis_bn': 'ইসম ইশারা (নির্দেশক সর্বনাম)',
        'desc_ms': 'Ini / itu (Kata tunjuk tunggal perempuan)',
        'jenis_ms': 'Isim Isyarat',
        'desc_fr': 'Celle-ci / Celle-là (Démonstratif singulier féminin)',
        'jenis_fr': 'Ism Isyarah (Démonstratif)',
        'desc_de': 'Diese / Jene (Demonstrativ Singular Femininum)',
        'jenis_de': 'Ism Isyarah (Demonstrativpronomen)',
        'desc_ur': 'یہ / وہ (واحد مؤنث، اسم اشارہ)',
        'jenis_ur': 'اسم اشارہ',
        'desc_hi': 'यह / वह (एकवचन स्त्री, संकेतवाचक सर्वनाम)',
        'jenis_hi': 'इस्म इशारा',
        'jenis_en': 'Ism Isyarah (Demonstrative)'
    },
    '5. Isyarah__4': {
        'desc_bn': 'ঐ সব / তা (দূরবর্তী নারী/ভগ্নাংশ বহুবচন নির্দেশক)',
        'jenis_bn': 'ইসম ইশারা (নির্দেশক সর্বনাম)',
        'desc_ms': 'Itu (Kata tunjuk jauh perempuan / jamak taksir)',
        'jenis_ms': 'Isim Isyarat',
        'desc_fr': 'Cela / Celles-là (Démonstratif lointain féminin/pluriel brisé)',
        'jenis_fr': 'Ism Isyarah (Démonstratif)',
        'desc_de': 'Jene / Jene Dinge (Fernes Demonstrativ Femininum/gebrochener Plural)',
        'jenis_de': 'Ism Isyarah (Demonstrativpronomen)',
        'desc_ur': 'وہ (بعید مؤنث / جمع مکسر، اسم اشارہ)',
        'jenis_ur': 'اسم اشارہ',
        'desc_hi': 'वह (दूरवर्ती स्त्रीलिंग / बहुवचन, संकेतवाचक)',
        'jenis_hi': 'इस्म इशारा',
        'jenis_en': 'Ism Isyarah (Demonstrative)'
    },
    '5. Isyarah__5': {
        'desc_bn': 'এখানে (নিকটবর্তী স্থান নির্দেশক শব্দ)',
        'jenis_bn': 'ইসম ইশারা মাকান (স্থান নির্দেশক)',
        'desc_ms': 'Di sini (Kata tunjuk tempat dekat)',
        'jenis_ms': 'Isim Isyarat Makan',
        'desc_fr': 'Ici (Démonstratif de lieu proche)',
        'jenis_fr': 'Ism Isyarah Makan (Lieu Proche)',
        'desc_de': 'Hier (Demonstrativ für nahen Ort)',
        'jenis_de': 'Ism Isyarah Makan (Naher Ort)',
        'desc_ur': 'یہاں (قریب جگہ کا اسم اشارہ)',
        'jenis_ur': 'اسم اشارہ مکان',
        'desc_hi': 'यहाँ (निकट स्थान का संकेतवाचक)',
        'jenis_hi': 'इस्म इशारा मकान',
        'jenis_en': 'Ism Isyarah Makan (Locative Demonstrative)'
    },
    '5. Isyarah__6': {
        'desc_bn': 'সেখানে (দূরবর্তী স্থান নির্দেশক শব্দ)',
        'jenis_bn': 'ইসম ইশারা মাকান (স্থান নির্দেশক)',
        'desc_ms': 'Di sana (Kata tunjuk tempat jauh)',
        'jenis_ms': 'Isim Isyarat Makan',
        'desc_fr': 'Là-bas / Là (Démonstratif de lieu distant)',
        'jenis_fr': 'Ism Isyarah Makan (Lieu Éloigné)',
        'desc_de': 'Dort (Demonstrativ für fernen Ort)',
        'jenis_de': 'Ism Isyarah Makan (Ferner Ort)',
        'desc_ur': 'وہاں (دور جگہ کا اسم اشارہ)',
        'jenis_ur': 'اسم اشارہ مکان',
        'desc_hi': 'वहाँ (दूर स्थान का संकेतवाचक)',
        'jenis_hi': 'इस्म इशारा मकान',
        'jenis_en': 'Ism Isyarah Makan (Locative Demonstrative)'
    },
    '5. Isyarah__7': {
        'desc_bn': 'এই দুজন (দ্বিবচন পুরুষ নির্দেশক সর্বনাম)',
        'jenis_bn': 'ইসম ইশারা (নির্দেশক সর্বনাম)',
        'desc_ms': 'Dua ini (Kata tunjuk ganda lelaki, Mu\'rab)',
        'jenis_ms': 'Isim Isyarat',
        'desc_fr': 'Ces deux-ci (Démonstratif duel masculin)',
        'jenis_fr': 'Ism Isyarah (Démonstratif)',
        'desc_de': 'Diese beiden Männer (Demonstrativ Dual Maskulinum)',
        'jenis_de': 'Ism Isyarah (Demonstrativpronomen)',
        'desc_ur': 'یہ دونوں مرد (تثنیہ مذکر، اسم اشارہ)',
        'jenis_ur': 'اسم اشارہ',
        'desc_hi': 'ये दोनों पुरुष (द्विवचन पुरुष, संकेतवाचक सर्वनाम)',
        'jenis_hi': 'इस्म इशारा',
        'jenis_en': 'Ism Isyarah (Demonstrative)'
    },
    '5. Isyarah__8': {
        'desc_bn': 'এই / ঐ দুজন নারী (দ্বিবচন নারী নির্দেশক সর্বনাম)',
        'jenis_bn': 'ইসম ইশারা (নির্দেশক সর্বনাম)',
        'desc_ms': 'Dua ini / itu (Kata tunjuk ganda perempuan, Mu\'rab)',
        'jenis_ms': 'Isim Isyarat',
        'desc_fr': 'Ces deux-ci / deux-là (Démonstratif duel féminin)',
        'jenis_fr': 'Ism Isyarah (Démonstratif)',
        'desc_de': 'Diese/Jene beiden Frauen (Demonstrativ Dual Femininum)',
        'jenis_de': 'Ism Isyarah (Demonstrativpronomen)',
        'desc_ur': 'وہ دونوں عورتیں (تثنیہ مؤنথ، اسم اشارہ)',
        'jenis_ur': 'اسم اشارہ',
        'desc_hi': 'वे दोनों स्त्रियां (द्विवचन स्त्री, संकेतवाचक सर्वनाम)',
        'jenis_hi': 'इस्म इशारा',
        'jenis_en': 'Ism Isyarah (Demonstrative)'
    },
    '6. Isim Fi\'il__1': {
        'desc_bn': 'মহাপবিত্র আল্লাহ (তাসবীহ ও পবিত্রতা ঘোষণার বিশেষ্য)',
        'jenis_bn': 'ইসম ফে\'ল / মাসদার',
        'desc_ms': 'Maha Suci (Isim Mashdar bermakna menyucikan Allah)',
        'jenis_ms': 'Isim Fi\'il / Mashdar',
        'desc_fr': 'Gloire à Allah / Pureté à Lui (Nom d\'action exprimant la glorification)',
        'jenis_fr': 'Ism Fi\'il / Masdar',
        'desc_de': 'Preis sei Allah (Verbalnomen zur Verherrlichung)',
        'jenis_de': 'Ism Fi\'il / Masdar',
        'desc_ur': 'پاک ہے اللہ (مصدری اسم برائے تسبیح و تنزیہ)',
        'jenis_ur': 'اسم فعل / مصدر',
        'desc_hi': 'महिमावान है अल्लाह (पवित्रता का भाववाचक शब्द)',
        'jenis_hi': 'इस्म फ़ेल / मस्तर',
        'jenis_en': 'Isim Fi\'il / Mashdar'
    },
    '6. Isim Fi\'il__2': {
        'desc_bn': 'তোমরা নিয়ে এসো / পেশ করো (আদেশসূচক ক্রিয়াভিত্তিক বিশেষ্য)',
        'jenis_bn': 'ইসম ফে\'লে আমর (আদেশসূচক)',
        'desc_ms': 'Tunjukkanlah / bawalah kemari bukti (Isim Fi\'il Amr)',
        'jenis_ms': 'Isim Fi\'il Amr',
        'desc_fr': 'Apportez / Produisez vos preuves (Nom verbal impératif)',
        'jenis_fr': 'Ism Fi\'il Amr (Impératif)',
        'desc_de': 'Bringt her / Legt vor (Imperatives Verbalnomen)',
        'jenis_de': 'Ism Fi\'il Amr (Imperativ)',
        'desc_ur': 'لاؤ / پیش کرو دلیل (اسم فعل امر)',
        'jenis_ur': 'اسم فعل امر',
        'desc_hi': 'लाओ / पेश करो प्रमाण (आज्ञार्थक क्रियार्थक संज्ञा)',
        'jenis_hi': 'इस्म फ़ेल अम्र',
        'jenis_en': 'Isim Fi\'il Amr (Imperative Verbal Noun)'
    },
    '6. Isim Fi\'il__3': {
        'desc_bn': 'ছিঃ / বিরক্তি ও আক্ষেপের অভিব্যক্তি (বর্তমানকালীন ক্রিয়াভিত্তিক বিশেষ্য)',
        'jenis_bn': 'ইসম ফে\'লে মুযারে\' (বর্তমানকালীন)',
        'desc_ms': 'Ungkapan rasa kesal / keluh kesah (Isim Fi\'il Mudhari\')',
        'jenis_ms': 'Isim Fi\'il Mudhari\'',
        'desc_fr': 'Fi ! / Expression de dégoût (Nom verbal au présent)',
        'jenis_fr': 'Ism Fi\'il Mudhari (Présent)',
        'desc_de': 'Pfui! / Ausdruck von Abscheu und Überdruss (Präsens-Verbalnomen)',
        'jenis_de': 'Ism Fi\'il Mudhari\' (Präsens)',
        'desc_ur': 'اف / بیزاری و اکتاہٹ کا کلمہ (اسم فعل مضارع)',
        'jenis_ur': 'اسم فعل مضارع',
        'desc_hi': 'उफ़ / घृणा व खीझ की अभिव्यक्ति (वर्तमान क्रियार्थक संज्ञा)',
        'jenis_hi': 'इस्म फ़ेल मुज़ारे',
        'jenis_en': 'Isim Fi\'il Mudhari\' (Present Verbal Noun)'
    },
    '6. Isim Fi\'il__4': {
        'desc_bn': 'আল্লাহর আশ্রয় প্রার্থনা করি (মাসদার)',
        'jenis_bn': 'ইসম ফে\'ল / মাসদার',
        'desc_ms': 'Aku berlindung kepada Allah (Ma\'ādzallāh)',
        'jenis_ms': 'Isim Fi\'il / Mashdar',
        'desc_fr': 'Qu\'Allah nous en préserve ! (Nom d\'action pour refuge)',
        'jenis_fr': 'Ism Fi\'il / Masdar',
        'desc_de': 'Zuflucht bei Allah (Verbalnomen für Schutzsuche)',
        'jenis_de': 'Ism Fi\'il / Masdar',
        'desc_ur': 'اللہ کی پناہ (معاذ اللہ، پناہ مانگنے کا مصدر)',
        'jenis_ur': 'اسم فعل / مصدر',
        'desc_hi': 'अल्लाह की शरण (शरण मांगने का भाववाचक शब्द)',
        'jenis_hi': 'इस्म फ़ेल / मस्तर',
        'jenis_en': 'Isim Fi\'il / Mashdar'
    },
    '6. Isim Fi\'il__5': {
        'desc_bn': 'এখানে এসো / উপস্থিত হও (আদেশসূচক ক্রিয়াভিত্তিক বিশেষ্য)',
        'jenis_bn': 'ইসম ফে\'লে আমর (আদেশসূচক)',
        'desc_ms': 'Kemarilah / bawalah kemari (Isim Fi\'il Amr)',
        'jenis_ms': 'Isim Fi\'il Amr',
        'desc_fr': 'Venez ici / Approchez (Nom verbal impératif)',
        'jenis_fr': 'Ism Fi\'il Amr (Impératif)',
        'desc_de': 'Kommt her / Bringt herbei (Imperatives Verbalnomen)',
        'jenis_de': 'Ism Fi\'il Amr (Imperativ)',
        'desc_ur': 'ادھر آؤ / لے کر آؤ (اسم فعل امر)',
        'jenis_ur': 'اسم فعل امر',
        'desc_hi': 'इधर आओ / पास आओ (आज्ञार्थक क्रियार्थक संज्ञा)',
        'jenis_hi': 'इस्म फ़ेल अम्र',
        'jenis_en': 'Isim Fi\'il Amr (Imperative Verbal Noun)'
    },
    '6. Isim Fi\'il__6': {
        'desc_bn': 'বহু দূর / অসম্ভব (অতীতকালীন ক্রিয়াভিত্তিক বিশেষ্য)',
        'jenis_bn': 'ইসম ফে\'লে মাদী (অতীতকালীন)',
        'desc_ms': 'Jauh sekali / mustahil terjadi (Isim Fi\'il Madhi)',
        'jenis_ms': 'Isim Fi\'il Madhi',
        'desc_fr': 'Que c\'est loin ! / Impossible (Nom verbal au passé)',
        'jenis_fr': 'Ism Fi\'il Madhi (Passé)',
        'desc_de': 'Wie weit entfernt! / Völlig unmöglich (Vergangenheit-Verbalnomen)',
        'jenis_de': 'Ism Fi\'il Madhi (Vergangenheit)',
        'desc_ur': 'بہت دور ہے / ناممکن ہے (اسم فعل ماضی)',
        'jenis_ur': 'اسم فعل ماضی',
        'desc_hi': 'बहुत दूर / सर्वथा असंभव (भूतकालिक क्रियार्थक संज्ञा)',
        'jenis_hi': 'इस्म फ़ेल माज़ी',
        'jenis_en': 'Isim Fi\'il Madhi (Past Verbal Noun)'
    },
    '6. Isim Fi\'il__7': {
        'desc_bn': 'এই নাও এবং পড়ো (আদেশসূচক ক্রিয়াভিত্তিক বিশেষ্য)',
        'jenis_bn': 'ইসম ফে\'লে আমর (আদেশসূচক)',
        'desc_ms': 'Ambillah dan bacalah ini (Isim Fi\'il Amr)',
        'jenis_ms': 'Isim Fi\'il Amr',
        'desc_fr': 'Tenez, prenez et lisez (Nom verbal impératif)',
        'jenis_fr': 'Ism Fi\'il Amr (Impératif)',
        'desc_de': 'Hier, nehmt und lest (Imperatives Verbalnomen)',
        'jenis_de': 'Ism Fi\'il Amr (Imperativ)',
        'desc_ur': 'لو یہ پکڑو اور پڑھو (اسم فعل امر)',
        'jenis_ur': 'اسم فعل امر',
        'desc_hi': 'लो इसे पकड़ो और पढ़ो (आज्ञार्थक क्रियार्थक संज्ञा)',
        'jenis_hi': 'इस्म फ़ेल अम्र',
        'jenis_en': 'Isim Fi\'il Amr (Imperative Verbal Noun)'
    },
    '6. Isim Fi\'il__8': {
        'desc_bn': 'এখানে এসো / প্রস্তুত হও (আদেশসূচক ক্রিয়াভিত্তিক বিশেষ্য)',
        'jenis_bn': 'ইসম ফে\'লে আমর (আদেশসূচক)',
        'desc_ms': 'Marilah kemari / bersiaplah (Isim Fi\'il Amr)',
        'jenis_ms': 'Isim Fi\'il Amr',
        'desc_fr': 'Viens donc ! / Je suis prête (Nom verbal impératif)',
        'jenis_fr': 'Ism Fi\'il Amr (Impératif)',
        'desc_de': 'Komm her! / Ich bin bereit (Imperatives Verbalnomen)',
        'jenis_de': 'Ism Fi\'il Amr (Imperativ)',
        'desc_ur': 'آ جاؤ / تیار ہو جاؤ (اسم فعل امر)',
        'jenis_ur': 'اسم فعل امر',
        'desc_hi': 'इधर आओ / तैयार हो जाओ (आज्ञार्थक क्रियार्थक संज्ञा)',
        'jenis_hi': 'इस्म फ़ेल अम्र',
        'jenis_en': 'Isim Fi\'il Amr (Imperative Verbal Noun)'
    },
    '7. Fi\'il Jamid__1': {
        'desc_bn': 'নয় / নেই (না-বোধক অপরিবর্তনীয় ক্রিয়া)',
        'jenis_bn': 'ফে\'লে মাদী জামিদ (অপরিবর্তনীয় অতীত ক্রিয়া)',
        'desc_ms': 'Bukan / tidak ada (Kata kerja kaku untuk penafian)',
        'jenis_ms': 'Fi\'il Madhi Jamid',
        'desc_fr': 'N\'est pas / Il n\'y a point (Verbe invariable de négation)',
        'jenis_fr': 'Fi\'il Madhi Jamid (Verbe Inflexible)',
        'desc_de': 'Ist nicht / Es gibt nicht (Erstarrtes Negationsverb)',
        'jenis_de': 'Fi\'il Madhi Jamid (Erstarrtes Verb)',
        'desc_ur': 'نہیں ہے / موجود نہیں (فعل جامد برائے نفی)',
        'jenis_ur': 'فعل ماضی جامد',
        'desc_hi': 'नहीं है / मौजूद नहीं (नकारार्थक रूढ़ क्रिया)',
        'jenis_hi': 'फ़ेल माज़ी जामिद',
        'jenis_en': 'Fi\'il Madhi Jamid (Inflexible Past Verb)'
    },
    '7. Fi\'il Jamid__2': {
        'desc_bn': 'কতই না নিকৃষ্ট / জঘন্য (নিন্দা ও অপছন্দের অপরিবর্তনীয় ক্রিয়া)',
        'jenis_bn': 'ফে\'লে মাদী জামিদ (অপরিবর্তনীয় অতীত ক্রিয়া)',
        'desc_ms': 'Seburuk-buruk (Kata kerja kaku untuk celaan / Adz-Dzamm)',
        'jenis_ms': 'Fi\'il Madhi Jamid',
        'desc_fr': 'Quel détestable / Quel mauvais (Verbe invariable de blâme)',
        'jenis_fr': 'Fi\'il Madhi Jamid (Verbe Inflexible)',
        'desc_de': 'Wie abscheulich / Wie übel ist (Erstarrtes Verb des Tadels)',
        'jenis_de': 'Fi\'il Madhi Jamid (Erstarrtes Verb)',
        'desc_ur': 'کیا ہی برا ہے (فعل جامد برائے مذمت)',
        'jenis_ur': 'فعل ماضی جامد',
        'desc_hi': 'कितना बुरा है (निंदार्थक रूढ़ क्रिया)',
        'jenis_hi': 'फ़ेल माज़ी जामिद',
        'jenis_en': 'Fi\'il Madhi Jamid (Inflexible Past Verb)'
    },
    '7. Fi\'il Jamid__3': {
        'desc_bn': 'সম্ভবত / আশা করা যায় (প্রত্যাশা ও সম্ভাবনার অপরিবর্তনীয় ক্রিয়া)',
        'jenis_bn': 'ফে\'লে মাদী জামিদ (অপরিবর্তনীয় অতীত ক্রিয়া)',
        'desc_ms': 'Semoga / boleh jadi (Kata kerja kaku untuk harapan / Tarajji)',
        'jenis_ms': 'Fi\'il Madhi Jamid',
        'desc_fr': 'Il se peut que / Peut-être (Verbe invariable d\'espoir)',
        'jenis_fr': 'Fi\'il Madhi Jamid (Verbe Inflexible)',
        'desc_de': 'Vielleicht / Es steht zu hoffen (Erstarrtes Verb der Hoffnung)',
        'jenis_de': 'Fi\'il Madhi Jamid (Erstarrtes Verb)',
        'desc_ur': 'شاید کہ / امید ہے کہ (فعل جامد برائے رجا و امید)',
        'jenis_ur': 'فعل ماضی جامد',
        'desc_hi': 'संभवतः / आशा है कि (आशार्थक रूढ़ क्रिया)',
        'jenis_hi': 'फ़ेल माज़ी जामिद',
        'jenis_en': 'Fi\'il Madhi Jamid (Inflexible Past Verb)'
    },
    '7. Fi\'il Jamid__4': {
        'desc_bn': 'কতই না উত্তম / চমৎকার (প্রশংসার অপরিবর্তনীয় ক্রিয়া)',
        'jenis_bn': 'ফে\'লে মাদী জামিদ (অপরিবর্তনীয় অতীত ক্রিয়া)',
        'desc_ms': 'Sebaik-baik (Kata kerja kaku untuk pujian / Al-Madh)',
        'jenis_ms': 'Fi\'il Madhi Jamid',
        'desc_fr': 'Quel excellent / Quel parfait (Verbe invariable d\'éloge)',
        'jenis_fr': 'Fi\'il Madhi Jamid (Verbe Inflexible)',
        'desc_de': 'Wie vortrefflich / Wie gut ist (Erstarrtes Verb des Lobes)',
        'jenis_de': 'Fi\'il Madhi Jamid (Erstarrtes Verb)',
        'desc_ur': 'کیا ہی بہترین ہے (فعل جامد برائے مدح و تعریف)',
        'jenis_ur': 'فعل ماضی جامد',
        'desc_hi': 'कितना उत्तम है (प्रशंसार्थक रूढ़ क्रिया)',
        'jenis_hi': 'फ़ेल माज़ी जामिद',
        'jenis_en': 'Fi\'il Madhi Jamid (Inflexible Past Verb)'
    },
    '7. Fi\'il Jamid__5': {
        'desc_bn': 'কতই না নিকৃষ্ট যা কিছু (যৌগিক নিন্দাসূচক ক্রিয়া)',
        'jenis_bn': 'ফে\'লে মাদী জামিদ (অপরিবর্তনীয় অতীত ক্রিয়া)',
        'desc_ms': 'Seburuk-buruk apa yang (Bi\'sa + Ma)',
        'jenis_ms': 'Fi\'il Madhi Jamid',
        'desc_fr': 'Combien est détestable ce que (Verbe composé de blâme)',
        'jenis_fr': 'Fi\'il Madhi Jamid (Verbe Inflexible)',
        'desc_de': 'Wie abscheulich ist das, was (Zusammengesetztes Tadelverb)',
        'jenis_de': 'Fi\'il Madhi Jamid (Erstarrtes Verb)',
        'desc_ur': 'کیا ہی برا ہے وہ جو (مرکب فعل برائے مذمت)',
        'jenis_ur': 'فعل ماضی جامد',
        'desc_hi': 'कितना बुरा है वह जो (संयुक्त निंदार्थक क्रिया)',
        'jenis_hi': 'फ़ेल माज़ी जामिद',
        'jenis_en': 'Fi\'il Madhi Jamid (Inflexible Past Verb)'
    },
    '7. Fi\'il Jamid__6': {
        'desc_bn': 'শুরু করলো / প্রবৃত্ত হলো (সূচনামূলক অপরিবর্তনীয় ক্রিয়া)',
        'jenis_bn': 'ফে\'লে মাদী জামিদ (অপরিবর্তনীয় অতীত ক্রিয়া)',
        'desc_ms': 'Mulai / bersegera melakukan (Af\'al Asy-Syuru\')',
        'jenis_ms': 'Fi\'il Madhi Jamid',
        'desc_fr': 'Se mirent à / Commencèrent à (Verbe d\'inchoation)',
        'jenis_fr': 'Fi\'il Madhi Jamid (Verbe Inflexible)',
        'desc_de': 'Begannen zu / Fingen an (Inchoatives Verb)',
        'jenis_de': 'Fi\'il Madhi Jamid (Erstarrtes Verb)',
        'desc_ur': 'لگ گئے / شروع کر دیا (فعل شروع)',
        'jenis_ur': 'فعل ماضی جامد',
        'desc_hi': 'आरंभ कर दिया / लग गए (प्रारंभिक रूढ़ क्रिया)',
        'jenis_hi': 'फ़ेल माज़ी जामिद',
        'jenis_en': 'Fi\'il Madhi Jamid (Inflexible Past Verb)'
    },
    '7. Fi\'il Jamid__7': {
        'desc_bn': 'আল্লাহর পবিত্রতা ঘোষণা করি / ত্রুটিমুক্ত (তানযীহ)',
        'jenis_bn': 'ফে\'লে জামিদ (অপরিবর্তনীয় ক্রিয়া)',
        'desc_ms': 'Maha Suci / jauh dari kekurangan (Tanzih)',
        'jenis_ms': 'Fi\'il Jamid',
        'desc_fr': 'À Dieu ne plaise / Pureté à Dieu (Verbe d\'exemption/Tanzih)',
        'jenis_fr': 'Fi\'il Jamid (Verbe Inflexible)',
        'desc_de': 'Gott bewahre / Fern sei Allah von Mängeln (Tanzih)',
        'jenis_de': 'Fi\'il Jamid (Erstarrtes Verb)',
        'desc_ur': 'حاش للہ / پاکی ہے اللہ کے لیے (فعل تنزیہ)',
        'jenis_ur': 'فعل جامد',
        'desc_hi': 'अल्लाह की पवित्रता (दोषमुक्ति क्रिया)',
        'jenis_hi': 'फ़ेल जामिद',
        'jenis_en': 'Fi\'il Jamid (Inflexible Verb)'
    },
    '7. Fi\'il Jamid__8': {
        'desc_bn': 'কতই না চমৎকার যা কিছু (যৌগিক প্রশংসাসূচক ক্রিয়া)',
        'jenis_bn': 'ফে\'লে মাদী জামিদ (অপরিবর্তনীয় অতীত ক্রিয়া)',
        'desc_ms': 'Sungguh sebaik-baik apa yang (Ni\'ma + Ma)',
        'jenis_ms': 'Fi\'il Madhi Jamid',
        'desc_fr': 'Combien est excellent ce que (Verbe composé d\'éloge)',
        'jenis_fr': 'Fi\'il Madhi Jamid (Verbe Inflexible)',
        'desc_de': 'Wie vortrefflich ist das, was (Zusammengesetztes Lobverb)',
        'jenis_de': 'Fi\'il Madhi Jamid (Erstarrtes Verb)',
        'desc_ur': 'کیا ہی خوب ہے وہ جو (مرکب فعل برائے مدح)',
        'jenis_ur': 'فعل ماضی جامد',
        'desc_hi': 'कितना उत्तम है वह जो (संयुक्त प्रशंसार्थक क्रिया)',
        'jenis_hi': 'फ़ेल माज़ी जामिद',
        'jenis_en': 'Fi\'il Madhi Jamid (Inflexible Past Verb)'
    }
}

# Update dhamir_data.json
with open('dhamir_data.json', 'r', encoding='utf-8') as f:
    dhamir_data = json.load(f)

for item in dhamir_data:
    b = item.get('Bentuk Kata')
    nk = item.get('No kata')
    key = f'{b}__{nk}'
    if key in metadata_updates:
        if 'Grammar' not in item or item['Grammar'] is None:
            item['Grammar'] = {}
        item['Grammar'].update(metadata_updates[key])

with open('dhamir_data.json', 'w', encoding='utf-8') as f:
    json.dump(dhamir_data, f, ensure_ascii=False, indent=2)

print(f'Successfully updated dhamir_data.json ({len(dhamir_data)} records)!')

# Update dhamir_data.js
js_content = f'''/**
 * Dataset Lengkap Multilingual Al-Qur'an 10 Bahasa (ID, EN, MS, FR, DE, UR, HI, BN, RU, ZH)
 * Total: {len(dhamir_data)} Rujukan Ayat
 */

const DHAMIR_DATA = {json.dumps(dhamir_data, ensure_ascii=False, indent=2)};
'''
with open('dhamir_data.js', 'w', encoding='utf-8') as f:
    f.write(js_content)

print(f'Successfully updated dhamir_data.js ({round(os.path.getsize("dhamir_data.js")/1024, 1)} KB)!')
