#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script Generator Dataset Multilingual (ID, EN, MS, FR)
Menghasilkan dhamir_data.json dan dhamir_data.js dengan terjemahan 4 bahasa:
- Bahasa Indonesia (Kementerian Agama RI)
- English (Sahih International)
- Bahasa Melayu (Syeikh Abdullah Muhammad Basmeih / JAKIM)
- Français (Muhammad Hamidullah / Le Saint Coran)
"""

import os
import json

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Database 114 Surat (ID, EN, MS, FR)
SURAHS = {
    1: {'nama': 'Al-Fatihah', 'arab': 'الفاتحة', 'arti_id': 'Pembukaan', 'arti_en': 'The Opening', 'arti_ms': 'Pembukaan', 'arti_fr': "L'Ouverture", 'ayat': 7},
    2: {'nama': 'Al-Baqarah', 'arab': 'البقرة', 'arti_id': 'Sapi Betina', 'arti_en': 'The Cow', 'arti_ms': 'Lembu Betina', 'arti_fr': 'La Vache', 'ayat': 286},
    3: {'nama': "Ali 'Imran", 'arab': 'آل عمران', 'arti_id': 'Keluarga Imran', 'arti_en': 'The Family of Imran', 'arti_ms': 'Keluarga Imran', 'arti_fr': "La Famille d'Imran", 'ayat': 200},
    4: {'nama': "An-Nisa'", 'arab': 'النساء', 'arti_id': 'Wanita', 'arti_en': 'The Women', 'arti_ms': 'Wanita', 'arti_fr': 'Les Femmes', 'ayat': 176},
    5: {'nama': "Al-Ma'idah", 'arab': 'المائدة', 'arti_id': 'Hidangan', 'arti_en': 'The Table Spread', 'arti_ms': 'Jamuan Hidangan', 'arti_fr': 'La Table Servie', 'ayat': 120},
    6: {'nama': "Al-An'am", 'arab': 'الأنعام', 'arti_id': 'Binatang Ternak', 'arti_en': 'The Cattle', 'arti_ms': 'Binatang Ternakan', 'arti_fr': 'Les Bestiaux', 'ayat': 165},
    7: {'nama': "Al-A'raf", 'arab': 'الأعراف', 'arti_id': 'Tempat yang Tertinggi', 'arti_en': 'The Heights', 'arti_ms': 'Tempat Tertinggi', 'arti_fr': "Les Murailles (Al-A'raf)", 'ayat': 206},
    8: {'nama': 'Al-Anfal', 'arab': 'الأنفال', 'arti_id': 'Harta Rampasan Perang', 'arti_en': 'The Spoils of War', 'arti_ms': 'Harta Rampasan Perang', 'arti_fr': 'Le Butin', 'ayat': 75},
    9: {'nama': 'At-Taubah', 'arab': 'التوبة', 'arti_id': 'Pengampunan', 'arti_en': 'The Repentance', 'arti_ms': 'Taubat', 'arti_fr': 'Le Repentir', 'ayat': 129},
    10: {'nama': 'Yunus', 'arab': 'يونس', 'arti_id': 'Nabi Yunus', 'arti_en': 'Jonah', 'arti_ms': 'Nabi Yunus', 'arti_fr': 'Jonas', 'ayat': 109},
    11: {'nama': 'Hud', 'arab': 'هود', 'arti_id': 'Nabi Hud', 'arti_en': 'Hud', 'arti_ms': 'Nabi Hud', 'arti_fr': 'Houd', 'ayat': 123},
    12: {'nama': 'Yusuf', 'arab': 'يوسف', 'arti_id': 'Nabi Yusuf', 'arti_en': 'Joseph', 'arti_ms': 'Nabi Yusuf', 'arti_fr': 'Joseph', 'ayat': 111},
    13: {'nama': "Ar-Ra'd", 'arab': 'الرعد', 'arti_id': 'Guruh', 'arti_en': 'The Thunder', 'arti_ms': 'Guruh', 'arti_fr': 'Le Tonnerre', 'ayat': 43},
    14: {'nama': 'Ibrahim', 'arab': 'إبراهيم', 'arti_id': 'Nabi Ibrahim', 'arti_en': 'Abraham', 'arti_ms': 'Nabi Ibrahim', 'arti_fr': 'Abraham', 'ayat': 52},
    15: {'nama': 'Al-Hijr', 'arab': 'الحجر', 'arti_id': 'Gunung Al-Hijr', 'arti_en': 'The Rocky Tract', 'arti_ms': 'Kawasan Berbatu / Al-Hijr', 'arti_fr': 'Al-Hijr', 'ayat': 99},
    16: {'nama': 'An-Nahl', 'arab': 'النحل', 'arti_id': 'Lebah', 'arti_en': 'The Bee', 'arti_ms': 'Lebah', 'arti_fr': 'Les Abeilles', 'ayat': 128},
    17: {'nama': "Al-Isra'", 'arab': 'الإسراء', 'arti_id': 'Perjalanan Malam', 'arti_en': 'The Night Journey', 'arti_ms': 'Perjalanan Malam', 'arti_fr': 'Le Voyage Nocturne', 'ayat': 111},
    18: {'nama': 'Al-Kahf', 'arab': 'الكهف', 'arti_id': 'Penghuni Gua', 'arti_en': 'The Cave', 'arti_ms': 'Gua', 'arti_fr': 'La Caverne', 'ayat': 110},
    19: {'nama': 'Maryam', 'arab': 'مريم', 'arti_id': 'Maryam', 'arti_en': 'Mary', 'arti_ms': 'Maryam', 'arti_fr': 'Marie', 'ayat': 98},
    20: {'nama': 'Taha', 'arab': 'طه', 'arti_id': 'Thaha', 'arti_en': 'Ta-Ha', 'arti_ms': 'Ta-Ha', 'arti_fr': 'Ta-Ha', 'ayat': 135},
    21: {'nama': "Al-Anbiya'", 'arab': 'الأنبياء', 'arti_id': 'Para Nabi', 'arti_en': 'The Prophets', 'arti_ms': 'Para Nabi', 'arti_fr': 'Les Prophètes', 'ayat': 112},
    22: {'nama': 'Al-Hajj', 'arab': 'الحج', 'arti_id': 'Haji', 'arti_en': 'The Pilgrimage', 'arti_ms': 'Haji', 'arti_fr': 'Le Pèlerinage', 'ayat': 78},
    23: {'nama': "Al-Mu'minun", 'arab': 'المؤمنون', 'arti_id': 'Orang-Orang Mukmin', 'arti_en': 'The Believers', 'arti_ms': 'Golongan yang Beriman', 'arti_fr': 'Les Croyants', 'ayat': 118},
    24: {'nama': 'An-Nur', 'arab': 'النور', 'arti_id': 'Cahaya', 'arti_en': 'The Light', 'arti_ms': 'Cahaya', 'arti_fr': 'La Lumière', 'ayat': 64},
    25: {'nama': 'Al-Furqan', 'arab': 'الفرقان', 'arti_id': 'Pembeda', 'arti_en': 'The Criterion', 'arti_ms': 'Pembeza', 'arti_fr': 'Le Discernement', 'ayat': 77},
    26: {'nama': "Asy-Syu'ara'", 'arab': 'الشعراء', 'arti_id': 'Penyair', 'arti_en': 'The Poets', 'arti_ms': 'Golongan Penyair', 'arti_fr': 'Les Poètes', 'ayat': 227},
    27: {'nama': 'An-Naml', 'arab': 'النمل', 'arti_id': 'Semut', 'arti_en': 'The Ants', 'arti_ms': 'Semut', 'arti_fr': 'Les Fourmis', 'ayat': 93},
    28: {'nama': 'Al-Qasas', 'arab': 'القصص', 'arti_id': 'Kisah-Kisah', 'arti_en': 'The Stories', 'arti_ms': 'Cerita-Cerita', 'arti_fr': 'Le Récit', 'ayat': 88},
    29: {'nama': "Al-'Ankabut", 'arab': 'العنكبوت', 'arti_id': 'Laba-Laba', 'arti_en': 'The Spider', 'arti_ms': 'Labah-Labah', 'arti_fr': "L'Araignée", 'ayat': 69},
    30: {'nama': 'Ar-Rum', 'arab': 'الروم', 'arti_id': 'Bangsa Romawi', 'arti_en': 'The Romans', 'arti_ms': 'Bangsa Rom', 'arti_fr': 'Les Romains', 'ayat': 60},
    31: {'nama': 'Luqman', 'arab': 'لقمان', 'arti_id': 'Luqman', 'arti_en': 'Luqman', 'arti_ms': 'Luqman', 'arti_fr': 'Luqman', 'ayat': 34},
    32: {'nama': 'As-Sajdah', 'arab': 'السجدة', 'arti_id': 'Sujud', 'arti_en': 'The Prostration', 'arti_ms': 'Sujud', 'arti_fr': 'La Prosternation', 'ayat': 30},
    33: {'nama': 'Al-Ahzab', 'arab': 'الأحزاب', 'arti_id': 'Golongan yang Bersekutu', 'arti_en': 'The Combined Forces', 'arti_ms': 'Golongan yang Bersekutu', 'arti_fr': 'Les Coalisés', 'ayat': 73},
    34: {'nama': "Saba'", 'arab': 'سبأ', 'arti_id': "Kaum Saba'", 'arti_en': 'Sheba', 'arti_ms': "Kaum Saba'", 'arti_fr': 'Saba', 'ayat': 54},
    35: {'nama': 'Fatir', 'arab': 'فاطر', 'arti_id': 'Pencipta', 'arti_en': 'The Originator', 'arti_ms': 'Pencipta', 'arti_fr': 'Le Créateur', 'ayat': 45},
    36: {'nama': 'Ya-Sin', 'arab': 'يس', 'arti_id': 'Ya Sin', 'arti_en': 'Ya-Sin', 'arti_ms': 'Ya Sin', 'arti_fr': 'Ya-Sin', 'ayat': 83},
    37: {'nama': 'As-Saffat', 'arab': 'الصافات', 'arti_id': 'Barisan-Barisan', 'arti_en': 'Those Ranked in Rows', 'arti_ms': 'Yang Berbaris Rapi', 'arti_fr': 'Les Rangés', 'ayat': 182},
    38: {'nama': 'Sad', 'arab': 'ص', 'arti_id': 'Shad', 'arti_en': 'The Letter Sad', 'arti_ms': 'Shad', 'arti_fr': 'Sad', 'ayat': 88},
    39: {'nama': 'Az-Zumar', 'arab': 'الزمر', 'arti_id': 'Rombongan', 'arti_en': 'The Groups', 'arti_ms': 'Rombongan', 'arti_fr': 'Les Groupes', 'ayat': 75},
    40: {'nama': 'Gafir', 'arab': 'غافر', 'arti_id': 'Yang Mengampuni', 'arti_en': 'The Forgiver', 'arti_ms': 'Yang Mengampunkan', 'arti_fr': 'Le Pardonneur', 'ayat': 85},
    41: {'nama': 'Fussilat', 'arab': 'فصلت', 'arti_id': 'Dijelaskan', 'arti_en': 'Distinguished Verses', 'arti_ms': 'Yang Dijelaskan', 'arti_fr': 'Les Versets Détaillés', 'ayat': 54},
    42: {'nama': 'Asy-Syura', 'arab': 'الشورى', 'arti_id': 'Musyawarah', 'arti_en': 'The Consultation', 'arti_ms': 'Musyawarah', 'arti_fr': 'La Consultation', 'ayat': 53},
    43: {'nama': 'Az-Zukhruf', 'arab': 'الزخرف', 'arti_id': 'Perhiasan', 'arti_en': 'The Gold Adornments', 'arti_ms': 'Perhiasan Emas', 'arti_fr': "L'Ornement", 'ayat': 89},
    44: {'nama': 'Ad-Dukhan', 'arab': 'الدخان', 'arti_id': 'Kabut', 'arti_en': 'The Smoke', 'arti_ms': 'Asap / Kabus', 'arti_fr': 'La Fumée', 'ayat': 59},
    45: {'nama': 'Al-Jasiyah', 'arab': 'الجاثية', 'arti_id': 'Yang Berlutut', 'arti_en': 'The Crouching', 'arti_ms': 'Yang Berlutut', 'arti_fr': "L'Agenouillée", 'ayat': 37},
    46: {'nama': 'Al-Ahqaf', 'arab': 'الأحقاف', 'arti_id': 'Bukit-Bukit Pasir', 'arti_en': 'The Wind-Curved Sandhills', 'arti_ms': 'Bukit Pasir', 'arti_fr': 'Al-Ahqaf', 'ayat': 35},
    47: {'nama': 'Muhammad', 'arab': 'محمد', 'arti_id': 'Nabi Muhammad', 'arti_en': 'Muhammad', 'arti_ms': 'Nabi Muhammad', 'arti_fr': 'Muhammad', 'ayat': 38},
    48: {'nama': 'Al-Fath', 'arab': 'الفتح', 'arti_id': 'Kemenangan', 'arti_en': 'The Victory', 'arti_ms': 'Kemenangan', 'arti_fr': 'La Victoire Éclatante', 'ayat': 29},
    49: {'nama': 'Al-Hujurat', 'arab': 'الحجرات', 'arti_id': 'Kamar-Kamar', 'arti_en': 'The Rooms', 'arti_ms': 'Bilik-Bilik', 'arti_fr': 'Les Appartements', 'ayat': 18},
    50: {'nama': 'Qaf', 'arab': 'ق', 'arti_id': 'Qaf', 'arti_en': 'The Letter Qaf', 'arti_ms': 'Qaf', 'arti_fr': 'Qaf', 'ayat': 45},
    51: {'nama': 'Az-Zariyat', 'arab': 'الذاريات', 'arti_id': 'Angin yang Menerbangkan', 'arti_en': 'The Winnowing Winds', 'arti_ms': 'Angin yang Menerbangkan', 'arti_fr': 'Qui Éparpillent', 'ayat': 60},
    52: {'nama': 'At-Tur', 'arab': 'الطور', 'arti_id': 'Bukit Tursina', 'arti_en': 'The Mount', 'arti_ms': 'Bukit Tursina', 'arti_fr': 'At-Tur', 'ayat': 49},
    53: {'nama': 'An-Najm', 'arab': 'النجم', 'arti_id': 'Bintang', 'arti_en': 'The Star', 'arti_ms': 'Bintang', 'arti_fr': "L'Étoile", 'ayat': 62},
    54: {'nama': 'Al-Qamar', 'arab': 'القمر', 'arti_id': 'Bulan', 'arti_en': 'The Moon', 'arti_ms': 'Bulan', 'arti_fr': 'La Lune', 'ayat': 55},
    55: {'nama': 'Ar-Rahman', 'arab': 'الرحمن', 'arti_id': 'Yang Maha Pengasih', 'arti_en': 'The Beneficent', 'arti_ms': 'Yang Maha Pemurah', 'arti_fr': 'Le Tout Miséricordieux', 'ayat': 78},
    56: {'nama': "Al-Waqi'ah", 'arab': 'الواقعة', 'arti_id': 'Hari Kiamat', 'arti_en': 'The Inevitable', 'arti_ms': 'Peristiwa Hari Kiamat', 'arti_fr': "L'Événement", 'ayat': 96},
    57: {'nama': 'Al-Hadid', 'arab': 'الحديد', 'arti_id': 'Besi', 'arti_en': 'The Iron', 'arti_ms': 'Besi', 'arti_fr': 'Le Fer', 'ayat': 29},
    58: {'nama': 'Al-Mujadilah', 'arab': 'المجادلة', 'arti_id': 'Gugatan', 'arti_en': 'The Pleading Woman', 'arti_ms': 'Perempuan yang Merayu', 'arti_fr': 'La Discussion', 'ayat': 22},
    59: {'nama': 'Al-Hasyr', 'arab': 'الحشر', 'arti_id': 'Pengusiran', 'arti_en': 'The Exile', 'arti_ms': 'Pengusiran', 'arti_fr': "L'Exode", 'ayat': 24},
    60: {'nama': 'Al-Mumtahanah', 'arab': 'الممتحنة', 'arti_id': 'Wanita yang Diuji', 'arti_en': 'The Examined One', 'arti_ms': 'Perempuan yang Diuji', 'arti_fr': "L'Éprouvée", 'ayat': 13},
    61: {'nama': 'As-Saff', 'arab': 'الصف', 'arti_id': 'Barisan', 'arti_en': 'The Ranks', 'arti_ms': 'Barisan', 'arti_fr': 'Le Rang', 'ayat': 14},
    62: {'nama': "Al-Jumu'ah", 'arab': 'الجمعة', 'arti_id': "Hari Jum'at", 'arti_en': 'Friday', 'arti_ms': 'Hari Jumaat', 'arti_fr': 'Le Vendredi', 'ayat': 11},
    63: {'nama': 'Al-Munafiqun', 'arab': 'المنافقون', 'arti_id': 'Orang-Orang Munafik', 'arti_en': 'The Hypocrites', 'arti_ms': 'Golongan Munafik', 'arti_fr': 'Les Hypocrites', 'ayat': 11},
    64: {'nama': 'At-Tagabun', 'arab': 'التغابن', 'arti_id': 'Pengungkapan Kesalahan', 'arti_en': 'Mutual Disillusion', 'arti_ms': 'Hari Terdedah Kerugian', 'arti_fr': 'La Grande Perte', 'ayat': 18},
    65: {'nama': 'At-Talaq', 'arab': 'الطلاق', 'arti_id': 'Talak', 'arti_en': 'The Divorce', 'arti_ms': 'Talak (Perceraian)', 'arti_fr': 'Le Divorce', 'ayat': 12},
    66: {'nama': 'At-Tahrim', 'arab': 'التحريم', 'arti_id': 'Pengharaman', 'arti_en': 'The Prohibition', 'arti_ms': 'Mengharamkan', 'arti_fr': "L'Interdiction", 'ayat': 12},
    67: {'nama': 'Al-Mulk', 'arab': 'الملك', 'arti_id': 'Kerajaan', 'arti_en': 'The Sovereignty', 'arti_ms': 'Kerajaan', 'arti_fr': 'La Royauté', 'ayat': 30},
    68: {'nama': 'Al-Qalam', 'arab': 'القلم', 'arti_id': 'Pena', 'arti_en': 'The Pen', 'arti_ms': 'Pena', 'arti_fr': 'La Plume', 'ayat': 52},
    69: {'nama': 'Al-Haqqah', 'arab': 'الحاقة', 'arti_id': 'Hari Kiamat yang Pasti', 'arti_en': 'The Inevitable Reality', 'arti_ms': 'Hari Kiamat yang Sebenar', 'arti_fr': "L'Inévitable", 'ayat': 52},
    70: {'nama': "Al-Ma'arij", 'arab': 'المعارج', 'arti_id': 'Tempat-Tempat Naik', 'arti_en': 'The Ascending Stairways', 'arti_ms': 'Tempat-Tempat Naik', 'arti_fr': "Les Voies d'Ascension", 'ayat': 44},
    71: {'nama': 'Nuh', 'arab': 'نوح', 'arti_id': 'Nabi Nuh', 'arti_en': 'Noah', 'arti_ms': 'Nabi Nuh', 'arti_fr': 'Noé', 'ayat': 28},
    72: {'nama': 'Al-Jinn', 'arab': 'الجن', 'arti_id': 'Jin', 'arti_en': 'The Jinn', 'arti_ms': 'Jin', 'arti_fr': 'Les Djinns', 'ayat': 28},
    73: {'nama': 'Al-Muzzammil', 'arab': 'المزمل', 'arti_id': 'Orang yang Berselimut', 'arti_en': 'The Enshrouded One', 'arti_ms': 'Yang Berselimut', 'arti_fr': "L'Enveloppé", 'ayat': 20},
    74: {'nama': 'Al-Muddassir', 'arab': 'المدثر', 'arti_id': 'Orang yang Berkemul', 'arti_en': 'The Cloaked One', 'arti_ms': 'Yang Berkemul', 'arti_fr': "Le Revêtu d'un Manteau", 'ayat': 56},
    75: {'nama': 'Al-Qiyamah', 'arab': 'القيامة', 'arti_id': 'Hari Kiamat', 'arti_en': 'The Resurrection', 'arti_ms': 'Hari Kiamat', 'arti_fr': 'La Résurrection', 'ayat': 40},
    76: {'nama': 'Al-Insan', 'arab': 'الإنسان', 'arti_id': 'Manusia', 'arti_en': 'Man', 'arti_ms': 'Manusia', 'arti_fr': "L'Homme", 'ayat': 31},
    77: {'nama': 'Al-Mursalat', 'arab': 'المرسلات', 'arti_id': 'Malaikat yang Diutus', 'arti_en': 'The Emissaries', 'arti_ms': 'Malaikat yang Diutus', 'arti_fr': 'Les Envoyés', 'ayat': 50},
    78: {'nama': "An-Naba'", 'arab': 'النبأ', 'arti_id': 'Berita Besar', 'arti_en': 'The Tidings', 'arti_ms': 'Berita Besar', 'arti_fr': 'La Nouvelle', 'ayat': 40},
    79: {'nama': "An-Nazi'at", 'arab': 'النازعات', 'arti_id': 'Malaikat Pencabut Nyawa', 'arti_en': 'Those Who Drag Forth', 'arti_ms': 'Malaikat yang Mencabut', 'arti_fr': 'Les Anges qui Arrachent', 'ayat': 46},
    80: {'nama': "'Abasa", 'arab': 'عبس', 'arti_id': 'Bermuka Masam', 'arti_en': 'He Frowned', 'arti_ms': 'Bermasam Muka', 'arti_fr': "Il s'est Renfrogné", 'ayat': 42},
    81: {'nama': 'At-Takwir', 'arab': 'التكوير', 'arti_id': 'Menggulung Matahari', 'arti_en': 'The Overthrowing', 'arti_ms': 'Menggulung Matahari', 'arti_fr': "L'Obscurcissement", 'ayat': 29},
    82: {'nama': 'Al-Infitar', 'arab': 'الانفطار', 'arti_id': 'Terbelah', 'arti_en': 'The Cleaving', 'arti_ms': 'Terbelah', 'arti_fr': 'La Rupture', 'ayat': 19},
    83: {'nama': 'Al-Mutaffifin', 'arab': 'المطففين', 'arti_id': 'Orang-Orang yang Curang', 'arti_en': 'The Defrauders', 'arti_ms': 'Golongan yang Curang', 'arti_fr': 'Les Fraudeurs', 'ayat': 36},
    84: {'nama': 'Al-Insyiqaq', 'arab': 'الانشقاق', 'arti_id': 'Terbelah', 'arti_en': 'The Splitting Open', 'arti_ms': 'Terbelah', 'arti_fr': 'La Déchirure', 'ayat': 25},
    85: {'nama': 'Al-Buruj', 'arab': 'البروج', 'arti_id': 'Gugusan Bintang', 'arti_en': 'The Mansions of the Stars', 'arti_ms': 'Gugusan Bintang', 'arti_fr': 'Les Constellations', 'ayat': 22},
    86: {'nama': 'At-Tariq', 'arab': 'الطارق', 'arti_id': 'Yang Datang di Malam Hari', 'arti_en': 'The Nightcomer', 'arti_ms': 'Pengunjung Malam', 'arti_fr': "L'Astre Nocturne", 'ayat': 17},
    87: {'nama': "Al-A'la", 'arab': 'الأعلى', 'arti_id': 'Yang Maha Tinggi', 'arti_en': 'The Most High', 'arti_ms': 'Yang Maha Tinggi', 'arti_fr': 'Le Très-Haut', 'ayat': 19},
    88: {'nama': 'Al-Gasyiyah', 'arab': 'الغاشية', 'arti_id': 'Hari Pembalasan yang Menyelimuti', 'arti_en': 'The Overwhelming Event', 'arti_ms': 'Hari Pembalasan yang Menyelubungi', 'arti_fr': "L'Enveloppante", 'ayat': 26},
    89: {'nama': 'Al-Fajr', 'arab': 'الفجر', 'arti_id': 'Fajar', 'arti_en': 'The Dawn', 'arti_ms': 'Waktu Fajar', 'arti_fr': "L'Aube", 'ayat': 30},
    90: {'nama': 'Al-Balad', 'arab': 'البلد', 'arti_id': 'Negeri', 'arti_en': 'The City', 'arti_ms': 'Negeri', 'arti_fr': 'La Cité', 'ayat': 20},
    91: {'nama': 'Asy-Syams', 'arab': 'الشمس', 'arti_id': 'Matahari', 'arti_en': 'The Sun', 'arti_ms': 'Matahari', 'arti_fr': 'Le Soleil', 'ayat': 15},
    92: {'nama': 'Al-Lail', 'arab': 'الليل', 'arti_id': 'Malam', 'arti_en': 'The Night', 'arti_ms': 'Malam', 'arti_fr': 'La Nuit', 'ayat': 21},
    93: {'nama': 'Ad-Duha', 'arab': 'الضحى', 'arti_id': 'Waktu Duha', 'arti_en': 'The Morning Brightness', 'arti_ms': 'Waktu Dhuha', 'arti_fr': 'Le Jour Montant', 'ayat': 11},
    94: {'nama': 'Asy-Syarh', 'arab': 'الشرح', 'arti_id': 'Kelapangan Dada', 'arti_en': 'The Relief', 'arti_ms': 'Melapangkan Dada', 'arti_fr': "L'Ouverture", 'ayat': 8},
    95: {'nama': 'At-Tin', 'arab': 'التين', 'arti_id': 'Buah Tin', 'arti_en': 'The Fig', 'arti_ms': 'Buah Tin', 'arti_fr': 'Le Figuier', 'ayat': 8},
    96: {'nama': "Al-'Alaq", 'arab': 'العلق', 'arti_id': 'Segumpal Darah', 'arti_en': 'The Clot', 'arti_ms': 'Segumpal Darah', 'arti_fr': "L'Adhérence", 'ayat': 19},
    97: {'nama': 'Al-Qadr', 'arab': 'القدر', 'arti_id': 'Kemuliaan', 'arti_en': 'The Night of Decree', 'arti_ms': 'Kemuliaan', 'arti_fr': 'La Destinée', 'ayat': 5},
    98: {'nama': 'Al-Bayyinah', 'arab': 'البينة', 'arti_id': 'Bukti Nyata', 'arti_en': 'The Clear Evidence', 'arti_ms': 'Bukti yang Nyata', 'arti_fr': 'La Preuve', 'ayat': 8},
    99: {'nama': 'Az-Zalzalah', 'arab': 'الزلزلة', 'arti_id': 'Guncangan', 'arti_en': 'The Earthquake', 'arti_ms': 'Kegoncangan', 'arti_fr': 'La Secousse', 'ayat': 8},
    100: {'nama': "Al-'Adiyat", 'arab': 'العاديات', 'arti_id': 'Kuda Perang yang Berlari Kencang', 'arti_en': 'The Courser', 'arti_ms': 'Kuda Perang yang Berlari Pantas', 'arti_fr': 'Les Coursiers', 'ayat': 11},
    101: {'nama': "Al-Qari'ah", 'arab': 'القارعة', 'arti_id': 'Hari Kiamat', 'arti_en': 'The Calamity', 'arti_ms': 'Hari Kiamat', 'arti_fr': 'Le Fracas', 'ayat': 11},
    102: {'nama': 'At-Takasur', 'arab': 'التكاثر', 'arti_id': 'Bermegah-Megahan', 'arti_en': 'The Rivalry in World Increase', 'arti_ms': 'Bermegah-Megahan', 'arti_fr': 'La Course aux Richesses', 'ayat': 8},
    103: {'nama': "Al-'Asr", 'arab': 'العصر', 'arti_id': 'Masa / Waktu Sore', 'arti_en': 'The Declining Day', 'arti_ms': 'Masa', 'arti_fr': 'Le Temps', 'ayat': 3},
    104: {'nama': 'Al-Humazah', 'arab': 'الهمزة', 'arti_id': 'Pengumpat', 'arti_en': 'The Traducer', 'arti_ms': 'Pengumpat', 'arti_fr': 'Les Calomniateurs', 'ayat': 9},
    105: {'nama': 'Al-Fil', 'arab': 'الفيل', 'arti_id': 'Gajah', 'arti_en': 'The Elephant', 'arti_ms': 'Gajah', 'arti_fr': "L'Éléphant", 'ayat': 5},
    106: {'nama': 'Quraisy', 'arab': 'قريش', 'arti_id': 'Suku Quraisy', 'arti_en': 'Quraysh', 'arti_ms': 'Kaum Quraisy', 'arti_fr': 'Qoraych', 'ayat': 4},
    107: {'nama': "Al-Ma'un", 'arab': 'الماعون', 'arti_id': 'Barang-Barang yang Berguna', 'arti_en': 'The Small Kindness', 'arti_ms': 'Barangan yang Berguna', 'arti_fr': "L'Ustensile", 'ayat': 7},
    108: {'nama': 'Al-Kausar', 'arab': 'الكوثر', 'arti_id': 'Nikmat yang Berlimpah', 'arti_en': 'The Abundance', 'arti_ms': 'Nikmat yang Melimpah', 'arti_fr': "L'Abondance", 'ayat': 3},
    109: {'nama': 'Al-Kafirun', 'arab': 'الكافرون', 'arti_id': 'Orang-Orang Kafir', 'arti_en': 'The Disbelievers', 'arti_ms': 'Golongan Kafir', 'arti_fr': 'Les Infidèles', 'ayat': 6},
    110: {'nama': 'An-Nasr', 'arab': 'النصر', 'arti_id': 'Pertolongan', 'arti_en': 'The Divine Help', 'arti_ms': 'Pertolongan', 'arti_fr': 'Les Secours', 'ayat': 3},
    111: {'nama': 'Al-Lahab', 'arab': 'اللهب', 'arti_id': 'Gejolak Api', 'arti_en': 'The Palm Fiber', 'arti_ms': 'Nyalaan Api', 'arti_fr': 'Les Fibres', 'ayat': 5},
    112: {'nama': 'Al-Ikhlas', 'arab': 'الإخلاص', 'arti_id': 'Kemurnian Keesaan Allah', 'arti_en': 'The Sincerity', 'arti_ms': 'Keikhlasan / Ketauhidan', 'arti_fr': 'Le Monothéisme Pur', 'ayat': 4},
    113: {'nama': 'Al-Falaq', 'arab': 'الفلق', 'arti_id': 'Waktu Subuh', 'arti_en': 'The Daybreak', 'arti_ms': 'Waktu Subuh', 'arti_fr': "L'Aube Naissante", 'ayat': 5},
    114: {'nama': 'An-Nas', 'arab': 'الناس', 'arti_id': 'Manusia', 'arti_en': 'Mankind', 'arti_ms': 'Manusia', 'arti_fr': 'Les Hommes', 'ayat': 6}
}

# Metadata Tata Bahasa Multilingual (ID, EN, MS, FR)
GRAMMATICAL_METADATA = {
    # --- 1. DHAMIR GHAIB (ORANG KE-3 / 3RD PERSON / 3E PERSONNE) ---
    '1a': {
        'latin': 'Huwa',
        'arti_id': 'DIA (LK)',
        'arti_en': 'HE / HIM',
        'arti_ms': 'DIA (LELAKI)',
        'arti_fr': 'IL / LUI',
        'desc_id': 'Dia (1 orang laki-laki)',
        'desc_en': 'He (Single Male, 3rd Person)',
        'desc_ms': 'Dia (1 orang lelaki)',
        'desc_fr': 'Il / Lui (1 personne masculin, 3e personne)',
        'jenis_id': 'Munfashil (Terpisah)',
        'jenis_en': 'Detached (Munfashil)',
        'jenis_ms': 'Munfashil (Berasingan)',
        'jenis_fr': 'Munfashil (Détaché / Isolé)',
        'dhamir_type_id': 'Ghaib (Orang ke-3)',
        'dhamir_type_en': '3rd Person (Ghaib)',
        'dhamir_type_ms': 'Ghaib (Orang ke-3)',
        'dhamir_type_fr': 'Ghaib (3e personne)',
        'gender_id': 'Mudzakkar (Laki-laki)',
        'gender_en': 'Masculine (Mudzakkar)',
        'gender_ms': 'Mudzakkar (Lelaki)',
        'gender_fr': 'Mudzakkar (Masculin)',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': "Rafa' (Subjek)",
        'posisi_en': 'Nominative (Subject)',
        'posisi_ms': "Rafa' (Subjek)",
        'posisi_fr': "Rafa' (Sujet / Nominatif)",
        'keterangan': 'Dia (1 orang laki-laki)'
    },
    '1b': {
        'latin': '..hu / ..hi',
        'arti_id': '..NYA (LK)',
        'arti_en': '..HIS / ..HIM',
        'arti_ms': '..NYA (LELAKI)',
        'arti_fr': '..SON / ..LUI',
        'desc_id': '...-nya (1 orang laki-laki)',
        'desc_en': 'His / Him (Single Male, 3rd Person)',
        'desc_ms': '...-nya (1 orang lelaki)',
        'desc_fr': '...son / ...lui (1 personne masculin, 3e personne)',
        'jenis_id': 'Muttashil (Tersambung)',
        'jenis_en': 'Attached (Muttashil)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'jenis_fr': 'Muttashil (Attaché / Suffixe)',
        'dhamir_type_id': 'Ghaib (Orang ke-3)',
        'dhamir_type_en': '3rd Person (Ghaib)',
        'dhamir_type_ms': 'Ghaib (Orang ke-3)',
        'dhamir_type_fr': 'Ghaib (3e personne)',
        'gender_id': 'Mudzakkar (Laki-laki)',
        'gender_en': 'Masculine (Mudzakkar)',
        'gender_ms': 'Mudzakkar (Lelaki)',
        'gender_fr': 'Mudzakkar (Masculin)',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': 'Nashab/Jar (Objek/Milik)',
        'posisi_en': 'Accusative/Genitive (Object/Possessive)',
        'posisi_ms': 'Nashab/Jar (Objek/Pemilikan)',
        'posisi_fr': 'Nashab/Jar (Objet / Possessif)',
        'keterangan': '...-nya (1 orang laki-laki)'
    },
    '2a': {
        'latin': 'Humā',
        'arti_id': 'MEREKA BERDUA (LK/PR)',
        'arti_en': 'THEY TWO (M/F)',
        'arti_ms': 'MEREKA BERDUA (L/P)',
        'arti_fr': 'EUX DEUX (M/F)',
        'desc_id': 'Mereka berdua (2 orang laki-laki / perempuan)',
        'desc_en': 'They two (Dual, 3rd Person M/F)',
        'desc_ms': 'Mereka berdua (2 orang lelaki / perempuan)',
        'desc_fr': 'Eux deux / Elles deux (Duel 3e personne M/F)',
        'jenis_id': 'Munfashil (Terpisah)',
        'jenis_en': 'Detached (Munfashil)',
        'jenis_ms': 'Munfashil (Berasingan)',
        'jenis_fr': 'Munfashil (Détaché / Isolé)',
        'dhamir_type_id': 'Ghaib (Orang ke-3)',
        'dhamir_type_en': '3rd Person (Ghaib)',
        'dhamir_type_ms': 'Ghaib (Orang ke-3)',
        'dhamir_type_fr': 'Ghaib (3e personne)',
        'gender_id': 'Mudzakkar / Muannats',
        'gender_en': 'Masculine / Feminine',
        'gender_ms': 'Mudzakkar / Muannats',
        'gender_fr': 'Masculin / Féminin',
        'bilangan_id': 'Mutsanna (Ganda/Dua)',
        'bilangan_en': 'Dual (Mutsanna)',
        'bilangan_ms': 'Mutsanna (Dua / Ganda)',
        'bilangan_fr': 'Mutsanna (Duel / Deux)',
        'posisi_id': "Rafa' (Subjek)",
        'posisi_en': 'Nominative (Subject)',
        'posisi_ms': "Rafa' (Subjek)",
        'posisi_fr': "Rafa' (Sujet / Nominatif)",
        'keterangan': 'Mereka berdua (2 orang L/P)'
    },
    '2b': {
        'latin': '..humā / ..himā',
        'arti_id': '..MEREKA BERDUA (LK/PR)',
        'arti_en': '..THEIR TWO / ..THEM TWO',
        'arti_ms': '..MEREKA BERDUA (L/P)',
        'arti_fr': '..LEUR DEUX / ..EUX DEUX',
        'desc_id': '...-mereka berdua (2 orang laki-laki / perempuan)',
        'desc_en': 'Their two / Them two (Dual, 3rd Person M/F)',
        'desc_ms': '...-mereka berdua (2 orang lelaki / perempuan)',
        'desc_fr': '...leur deux / ...eux deux (Duel 3e personne M/F)',
        'jenis_id': 'Muttashil (Tersambung)',
        'jenis_en': 'Attached (Muttashil)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'jenis_fr': 'Muttashil (Attaché / Suffixe)',
        'dhamir_type_id': 'Ghaib (Orang ke-3)',
        'dhamir_type_en': '3rd Person (Ghaib)',
        'dhamir_type_ms': 'Ghaib (Orang ke-3)',
        'dhamir_type_fr': 'Ghaib (3e personne)',
        'gender_id': 'Mudzakkar / Muannats',
        'gender_en': 'Masculine / Feminine',
        'gender_ms': 'Mudzakkar / Muannats',
        'gender_fr': 'Masculin / Féminin',
        'bilangan_id': 'Mutsanna (Ganda/Dua)',
        'bilangan_en': 'Dual (Mutsanna)',
        'bilangan_ms': 'Mutsanna (Dua / Ganda)',
        'bilangan_fr': 'Mutsanna (Duel / Deux)',
        'posisi_id': 'Nashab/Jar (Objek/Milik)',
        'posisi_en': 'Accusative/Genitive (Object/Possessive)',
        'posisi_ms': 'Nashab/Jar (Objek/Pemilikan)',
        'posisi_fr': 'Nashab/Jar (Objet / Possessif)',
        'keterangan': '...-mereka berdua (2 orang L/P)'
    },
    '3a': {
        'latin': 'Hum',
        'arti_id': 'MEREKA (LK)',
        'arti_en': 'THEY (MASC)',
        'arti_ms': 'MEREKA (LELAKI)',
        'arti_fr': 'ILS / EUX',
        'desc_id': 'Mereka (banyak laki-laki)',
        'desc_en': 'They (Plural Male, 3rd Person)',
        'desc_ms': 'Mereka (ramai lelaki)',
        'desc_fr': 'Ils / Eux (Pluriel masculin, 3e personne)',
        'jenis_id': 'Munfashil (Terpisah)',
        'jenis_en': 'Detached (Munfashil)',
        'jenis_ms': 'Munfashil (Berasingan)',
        'jenis_fr': 'Munfashil (Détaché / Isolé)',
        'dhamir_type_id': 'Ghaib (Orang ke-3)',
        'dhamir_type_en': '3rd Person (Ghaib)',
        'dhamir_type_ms': 'Ghaib (Orang ke-3)',
        'dhamir_type_fr': 'Ghaib (3e personne)',
        'gender_id': 'Mudzakkar (Laki-laki)',
        'gender_en': 'Masculine (Mudzakkar)',
        'gender_ms': 'Mudzakkar (Lelaki)',
        'gender_fr': 'Mudzakkar (Masculin)',
        'bilangan_id': 'Jamak (Banyak)',
        'bilangan_en': 'Plural (Jamak)',
        'bilangan_ms': 'Jamak (Ramai)',
        'bilangan_fr': 'Jamak (Pluriel)',
        'posisi_id': "Rafa' (Subjek)",
        'posisi_en': 'Nominative (Subject)',
        'posisi_ms': "Rafa' (Subjek)",
        'posisi_fr': "Rafa' (Sujet / Nominatif)",
        'keterangan': 'Mereka (banyak laki-laki)'
    },
    '3b': {
        'latin': '..hum / ..him',
        'arti_id': '..MEREKA (LK)',
        'arti_en': '..THEIR / ..THEM',
        'arti_ms': '..MEREKA (LELAKI)',
        'arti_fr': '..LEUR / ..EUX',
        'desc_id': '...-mereka (banyak laki-laki)',
        'desc_en': 'Their / Them (Plural Male, 3rd Person)',
        'desc_ms': '...-mereka (ramai lelaki)',
        'desc_fr': '...leur / ...eux (Pluriel masculin, 3e personne)',
        'jenis_id': 'Muttashil (Tersambung)',
        'jenis_en': 'Attached (Muttashil)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'jenis_fr': 'Muttashil (Attaché / Suffixe)',
        'dhamir_type_id': 'Ghaib (Orang ke-3)',
        'dhamir_type_en': '3rd Person (Ghaib)',
        'dhamir_type_ms': 'Ghaib (Orang ke-3)',
        'dhamir_type_fr': 'Ghaib (3e personne)',
        'gender_id': 'Mudzakkar (Laki-laki)',
        'gender_en': 'Masculine (Mudzakkar)',
        'gender_ms': 'Mudzakkar (Lelaki)',
        'gender_fr': 'Mudzakkar (Masculin)',
        'bilangan_id': 'Jamak (Banyak)',
        'bilangan_en': 'Plural (Jamak)',
        'bilangan_ms': 'Jamak (Ramai)',
        'bilangan_fr': 'Jamak (Pluriel)',
        'posisi_id': 'Nashab/Jar (Objek/Milik)',
        'posisi_en': 'Accusative/Genitive (Object/Possessive)',
        'posisi_ms': 'Nashab/Jar (Objek/Pemilikan)',
        'posisi_fr': 'Nashab/Jar (Objet / Possessif)',
        'keterangan': '...-mereka (banyak laki-laki)'
    },
    '4a': {
        'latin': 'Hiya',
        'arti_id': 'DIA (PR)',
        'arti_en': 'SHE / HER',
        'arti_ms': 'DIA (PEREMPUAN)',
        'arti_fr': 'ELLE',
        'desc_id': 'Dia (1 orang perempuan)',
        'desc_en': 'She (Single Female, 3rd Person)',
        'desc_ms': 'Dia (1 orang perempuan)',
        'desc_fr': 'Elle (1 personne féminin, 3e personne)',
        'jenis_id': 'Munfashil (Terpisah)',
        'jenis_en': 'Detached (Munfashil)',
        'jenis_ms': 'Munfashil (Berasingan)',
        'jenis_fr': 'Munfashil (Détaché / Isolé)',
        'dhamir_type_id': 'Ghaib (Orang ke-3)',
        'dhamir_type_en': '3rd Person (Ghaib)',
        'dhamir_type_ms': 'Ghaib (Orang ke-3)',
        'dhamir_type_fr': 'Ghaib (3e personne)',
        'gender_id': 'Muannats (Perempuan)',
        'gender_en': 'Feminine (Muannats)',
        'gender_ms': 'Muannats (Perempuan)',
        'gender_fr': 'Muannats (Féminin)',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': "Rafa' (Subjek)",
        'posisi_en': 'Nominative (Subject)',
        'posisi_ms': "Rafa' (Subjek)",
        'posisi_fr': "Rafa' (Sujet / Nominatif)",
        'keterangan': 'Dia (1 orang perempuan)'
    },
    '4b': {
        'latin': '..hā',
        'arti_id': '..NYA (PR)',
        'arti_en': '..HER',
        'arti_ms': '..NYA (PEREMPUAN)',
        'arti_fr': '..SA / ..ELLE',
        'desc_id': '...-nya (1 orang perempuan)',
        'desc_en': 'Her (Single Female, 3rd Person)',
        'desc_ms': '...-nya (1 orang perempuan)',
        'desc_fr': '...sa / ...elle (1 personne féminin, 3e personne)',
        'jenis_id': 'Muttashil (Tersambung)',
        'jenis_en': 'Attached (Muttashil)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'jenis_fr': 'Muttashil (Attaché / Suffixe)',
        'dhamir_type_id': 'Ghaib (Orang ke-3)',
        'dhamir_type_en': '3rd Person (Ghaib)',
        'dhamir_type_ms': 'Ghaib (Orang ke-3)',
        'dhamir_type_fr': 'Ghaib (3e personne)',
        'gender_id': 'Muannats (Perempuan)',
        'gender_en': 'Feminine (Muannats)',
        'gender_ms': 'Muannats (Perempuan)',
        'gender_fr': 'Muannats (Féminin)',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': 'Nashab/Jar (Objek/Milik)',
        'posisi_en': 'Accusative/Genitive (Object/Possessive)',
        'posisi_ms': 'Nashab/Jar (Objek/Pemilikan)',
        'posisi_fr': 'Nashab/Jar (Objet / Possessif)',
        'keterangan': '...-nya (1 orang perempuan)'
    },
    '5a': {
        'latin': 'Hunna',
        'arti_id': 'MEREKA (PR)',
        'arti_en': 'THEY (FEM)',
        'arti_ms': 'MEREKA (PEREMPUAN)',
        'arti_fr': 'ELLES',
        'desc_id': 'Mereka (banyak perempuan)',
        'desc_en': 'They (Plural Female, 3rd Person)',
        'desc_ms': 'Mereka (ramai perempuan)',
        'desc_fr': 'Elles (Pluriel féminin, 3e personne)',
        'jenis_id': 'Munfashil (Terpisah)',
        'jenis_en': 'Detached (Munfashil)',
        'jenis_ms': 'Munfashil (Berasingan)',
        'jenis_fr': 'Munfashil (Détaché / Isolé)',
        'dhamir_type_id': 'Ghaib (Orang ke-3)',
        'dhamir_type_en': '3rd Person (Ghaib)',
        'dhamir_type_ms': 'Ghaib (Orang ke-3)',
        'dhamir_type_fr': 'Ghaib (3e personne)',
        'gender_id': 'Muannats (Perempuan)',
        'gender_en': 'Feminine (Muannats)',
        'gender_ms': 'Muannats (Perempuan)',
        'gender_fr': 'Muannats (Féminin)',
        'bilangan_id': 'Jamak (Banyak)',
        'bilangan_en': 'Plural (Jamak)',
        'bilangan_ms': 'Jamak (Ramai)',
        'bilangan_fr': 'Jamak (Pluriel)',
        'posisi_id': "Rafa' (Subjek)",
        'posisi_en': 'Nominative (Subject)',
        'posisi_ms': "Rafa' (Subjek)",
        'posisi_fr': "Rafa' (Sujet / Nominatif)",
        'keterangan': 'Mereka (banyak perempuan)'
    },
    '5b': {
        'latin': '..hunna / ..hinna',
        'arti_id': '..MEREKA (PR)',
        'arti_en': '..THEIR / ..THEM (FEM)',
        'arti_ms': '..MEREKA (PEREMPUAN)',
        'arti_fr': '..LEUR / ..ELLES',
        'desc_id': '...-mereka (banyak perempuan)',
        'desc_en': 'Their / Them (Plural Female, 3rd Person)',
        'desc_ms': '...-mereka (ramai perempuan)',
        'desc_fr': '...leur / ...elles (Pluriel féminin, 3e personne)',
        'jenis_id': 'Muttashil (Tersambung)',
        'jenis_en': 'Attached (Muttashil)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'jenis_fr': 'Muttashil (Attaché / Suffixe)',
        'dhamir_type_id': 'Ghaib (Orang ke-3)',
        'dhamir_type_en': '3rd Person (Ghaib)',
        'dhamir_type_ms': 'Ghaib (Orang ke-3)',
        'dhamir_type_fr': 'Ghaib (3e personne)',
        'gender_id': 'Muannats (Perempuan)',
        'gender_en': 'Feminine (Muannats)',
        'gender_ms': 'Muannats (Perempuan)',
        'gender_fr': 'Muannats (Féminin)',
        'bilangan_id': 'Jamak (Banyak)',
        'bilangan_en': 'Plural (Jamak)',
        'bilangan_ms': 'Jamak (Ramai)',
        'bilangan_fr': 'Jamak (Pluriel)',
        'posisi_id': 'Nashab/Jar (Objek/Milik)',
        'posisi_en': 'Accusative/Genitive (Object/Possessive)',
        'posisi_ms': 'Nashab/Jar (Objek/Pemilikan)',
        'posisi_fr': 'Nashab/Jar (Objet / Possessif)',
        'keterangan': '...-mereka (banyak perempuan)'
    },

    # --- 2. DHAMIR MUKHATAB (ORANG KE-2 / 2ND PERSON / 2E PERSONNE) ---
    '6a': {
        'latin': 'Anta',
        'arti_id': 'KAMU (LK)',
        'arti_en': 'YOU (MASC)',
        'arti_ms': 'ENGKAU / KAMU (LELAKI)',
        'arti_fr': 'TOI / TU (M)',
        'desc_id': 'Kamu / Engkau (1 orang laki-laki)',
        'desc_en': 'You (Single Male, 2nd Person)',
        'desc_ms': 'Engkau / Kamu (1 orang lelaki)',
        'desc_fr': 'Toi / Tu (1 personne masculin, 2e personne)',
        'jenis_id': 'Munfashil (Terpisah)',
        'jenis_en': 'Detached (Munfashil)',
        'jenis_ms': 'Munfashil (Berasingan)',
        'jenis_fr': 'Munfashil (Détaché / Isolé)',
        'dhamir_type_id': 'Mukhatab (Orang ke-2)',
        'dhamir_type_en': '2nd Person (Mukhatab)',
        'dhamir_type_ms': 'Mukhatab (Orang ke-2)',
        'dhamir_type_fr': 'Mukhatab (2e personne)',
        'gender_id': 'Mudzakkar (Laki-laki)',
        'gender_en': 'Masculine (Mudzakkar)',
        'gender_ms': 'Mudzakkar (Lelaki)',
        'gender_fr': 'Mudzakkar (Masculin)',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': "Rafa' (Subjek)",
        'posisi_en': 'Nominative (Subject)',
        'posisi_ms': "Rafa' (Subjek)",
        'posisi_fr': "Rafa' (Sujet / Nominatif)",
        'keterangan': 'Kamu / Engkau (1 orang laki-laki)'
    },
    '6b': {
        'latin': '..ka',
        'arti_id': '..MU (LK)',
        'arti_en': '..YOUR / ..YOU',
        'arti_ms': '..MU (LELAKI)',
        'arti_fr': '..TON / ..TOI (M)',
        'desc_id': '...-mu (1 orang laki-laki)',
        'desc_en': 'Your / You (Single Male, 2nd Person)',
        'desc_ms': '...-mu (1 orang lelaki)',
        'desc_fr': '...ton / ...toi (1 personne masculin, 2e personne)',
        'jenis_id': 'Muttashil (Tersambung)',
        'jenis_en': 'Attached (Muttashil)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'jenis_fr': 'Muttashil (Attaché / Suffixe)',
        'dhamir_type_id': 'Mukhatab (Orang ke-2)',
        'dhamir_type_en': '2nd Person (Mukhatab)',
        'dhamir_type_ms': 'Mukhatab (Orang ke-2)',
        'dhamir_type_fr': 'Mukhatab (2e personne)',
        'gender_id': 'Mudzakkar (Laki-laki)',
        'gender_en': 'Masculine (Mudzakkar)',
        'gender_ms': 'Mudzakkar (Lelaki)',
        'gender_fr': 'Mudzakkar (Masculin)',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': 'Nashab/Jar (Objek/Milik)',
        'posisi_en': 'Accusative/Genitive (Object/Possessive)',
        'posisi_ms': 'Nashab/Jar (Objek/Pemilikan)',
        'posisi_fr': 'Nashab/Jar (Objet / Possessif)',
        'keterangan': '...-mu (1 orang laki-laki)'
    },
    '6c': {
        'latin': 'Iyyāka',
        'arti_id': 'HANYA KEPADAMU (LK)',
        'arti_en': 'YOU ALONE (MASC)',
        'arti_ms': 'HANYA KEPADA-MU (LELAKI)',
        'arti_fr': 'TOI SEUL (M)',
        'desc_id': 'Hanya kepada-Mu (1 orang laki-laki)',
        'desc_en': 'You alone / Unto You only (Single Male, 2nd Person)',
        'desc_ms': 'Hanya kepada-Mu (1 orang lelaki)',
        'desc_fr': "C'est Toi Seul / À Toi Seul (1 personne masculin, 2e personne)",
        'jenis_id': 'Munfashil (Terpisah - Iyyaka)',
        'jenis_en': 'Detached (Munfashil - Iyyaka)',
        'jenis_ms': 'Munfashil (Berasingan - Iyyaka)',
        'jenis_fr': 'Munfashil (Détaché - Iyyaka)',
        'dhamir_type_id': 'Mukhatab (Orang ke-2)',
        'dhamir_type_en': '2nd Person (Mukhatab)',
        'dhamir_type_ms': 'Mukhatab (Orang ke-2)',
        'dhamir_type_fr': 'Mukhatab (2e personne)',
        'gender_id': 'Mudzakkar (Laki-laki)',
        'gender_en': 'Masculine (Mudzakkar)',
        'gender_ms': 'Mudzakkar (Lelaki)',
        'gender_fr': 'Mudzakkar (Masculin)',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': 'Nashab (Objek Khusus)',
        'posisi_en': 'Accusative (Exclusive Object)',
        'posisi_ms': 'Nashab (Objek Khusus)',
        'posisi_fr': 'Nashab (Objet exclusif)',
        'keterangan': 'Hanya kepada-Mu (1 orang laki-laki)'
    },
    '7a': {
        'latin': 'Antumā',
        'arti_id': 'KALIAN BERDUA (LK/PR)',
        'arti_en': 'YOU TWO (M/F)',
        'arti_ms': 'KAMU BERDUA (L/P)',
        'arti_fr': 'VOUS DEUX (M/F)',
        'desc_id': 'Kalian berdua (2 orang L/P)',
        'desc_en': 'You two (Dual 2nd Person M/F)',
        'desc_ms': 'Kamu berdua (2 orang L/P)',
        'desc_fr': 'Vous deux (Duel 2e personne M/F)',
        'jenis_id': 'Munfashil (Terpisah)',
        'jenis_en': 'Detached (Munfashil)',
        'jenis_ms': 'Munfashil (Berasingan)',
        'jenis_fr': 'Munfashil (Détaché / Isolé)',
        'dhamir_type_id': 'Mukhatab (Orang ke-2)',
        'dhamir_type_en': '2nd Person (Mukhatab)',
        'dhamir_type_ms': 'Mukhatab (Orang ke-2)',
        'dhamir_type_fr': 'Mukhatab (2e personne)',
        'gender_id': 'Mudzakkar / Muannats',
        'gender_en': 'Masculine / Feminine',
        'gender_ms': 'Mudzakkar / Muannats',
        'gender_fr': 'Masculin / Féminin',
        'bilangan_id': 'Mutsanna (Ganda/Dua)',
        'bilangan_en': 'Dual (Mutsanna)',
        'bilangan_ms': 'Mutsanna (Dua / Ganda)',
        'bilangan_fr': 'Mutsanna (Duel / Deux)',
        'posisi_id': "Rafa' (Subjek)",
        'posisi_en': 'Nominative (Subject)',
        'posisi_ms': "Rafa' (Subjek)",
        'posisi_fr': "Rafa' (Sujet / Nominatif)",
        'keterangan': 'Kalian berdua (2 orang L/P)'
    },
    '7b': {
        'latin': '..kumā',
        'arti_id': '..KALIAN BERDUA (LK/PR)',
        'arti_en': '..YOUR TWO / ..YOU TWO',
        'arti_ms': '..KAMU BERDUA (L/P)',
        'arti_fr': '..VOTRE DEUX / ..VOUS DEUX',
        'desc_id': '...-kalian berdua (2 orang L/P)',
        'desc_en': 'Your two / You two (Dual 2nd Person M/F)',
        'desc_ms': '...-kamu berdua (2 orang L/P)',
        'desc_fr': '...votre deux / ...vous deux (Duel 2e personne M/F)',
        'jenis_id': 'Muttashil (Tersambung)',
        'jenis_en': 'Attached (Muttashil)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'jenis_fr': 'Muttashil (Attaché / Suffixe)',
        'dhamir_type_id': 'Mukhatab (Orang ke-2)',
        'dhamir_type_en': '2nd Person (Mukhatab)',
        'dhamir_type_ms': 'Mukhatab (Orang ke-2)',
        'dhamir_type_fr': 'Mukhatab (2e personne)',
        'gender_id': 'Mudzakkar / Muannats',
        'gender_en': 'Masculine / Feminine',
        'gender_ms': 'Mudzakkar / Muannats',
        'gender_fr': 'Masculin / Féminin',
        'bilangan_id': 'Mutsanna (Ganda/Dua)',
        'bilangan_en': 'Dual (Mutsanna)',
        'bilangan_ms': 'Mutsanna (Dua / Ganda)',
        'bilangan_fr': 'Mutsanna (Duel / Deux)',
        'posisi_id': 'Nashab/Jar (Objek/Milik)',
        'posisi_en': 'Accusative/Genitive (Object/Possessive)',
        'posisi_ms': 'Nashab/Jar (Objek/Pemilikan)',
        'posisi_fr': 'Nashab/Jar (Objet / Possessif)',
        'keterangan': '...-kalian berdua (2 orang L/P)'
    },
    '8a': {
        'latin': 'Antum',
        'arti_id': 'KALIAN (LK)',
        'arti_en': 'YOU ALL (MASC)',
        'arti_ms': 'KAMU SEMUA (LELAKI)',
        'arti_fr': 'VOUS (M PLURIEL)',
        'desc_id': 'Kalian (banyak laki-laki)',
        'desc_en': 'You all (Plural Male, 2nd Person)',
        'desc_ms': 'Kamu semua (ramai lelaki)',
        'desc_fr': 'Vous (Pluriel masculin, 2e personne)',
        'jenis_id': 'Munfashil (Terpisah)',
        'jenis_en': 'Detached (Munfashil)',
        'jenis_ms': 'Munfashil (Berasingan)',
        'jenis_fr': 'Munfashil (Détaché / Isolé)',
        'dhamir_type_id': 'Mukhatab (Orang ke-2)',
        'dhamir_type_en': '2nd Person (Mukhatab)',
        'dhamir_type_ms': 'Mukhatab (Orang ke-2)',
        'dhamir_type_fr': 'Mukhatab (2e personne)',
        'gender_id': 'Mudzakkar (Laki-laki)',
        'gender_en': 'Masculine (Mudzakkar)',
        'gender_ms': 'Mudzakkar (Lelaki)',
        'gender_fr': 'Mudzakkar (Masculin)',
        'bilangan_id': 'Jamak (Banyak)',
        'bilangan_en': 'Plural (Jamak)',
        'bilangan_ms': 'Jamak (Ramai)',
        'bilangan_fr': 'Jamak (Pluriel)',
        'posisi_id': "Rafa' (Subjek)",
        'posisi_en': 'Nominative (Subject)',
        'posisi_ms': "Rafa' (Subjek)",
        'posisi_fr': "Rafa' (Sujet / Nominatif)",
        'keterangan': 'Kalian (banyak laki-laki)'
    },
    '8b': {
        'latin': '..kum',
        'arti_id': '..KALIAN (LK)',
        'arti_en': '..YOUR / ..YOU ALL',
        'arti_ms': '..KAMU SEMUA (LELAKI)',
        'arti_fr': '..VOTRE / ..VOUS (M)',
        'desc_id': '...-kalian (banyak laki-laki)',
        'desc_en': 'Your / You all (Plural Male, 2nd Person)',
        'desc_ms': '...-kamu semua (ramai lelaki)',
        'desc_fr': '...votre / ...vous (Pluriel masculin, 2e personne)',
        'jenis_id': 'Muttashil (Tersambung)',
        'jenis_en': 'Attached (Muttashil)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'jenis_fr': 'Muttashil (Attaché / Suffixe)',
        'dhamir_type_id': 'Mukhatab (Orang ke-2)',
        'dhamir_type_en': '2nd Person (Mukhatab)',
        'dhamir_type_ms': 'Mukhatab (Orang ke-2)',
        'dhamir_type_fr': 'Mukhatab (2e personne)',
        'gender_id': 'Mudzakkar (Laki-laki)',
        'gender_en': 'Masculine (Mudzakkar)',
        'gender_ms': 'Mudzakkar (Lelaki)',
        'gender_fr': 'Mudzakkar (Masculin)',
        'bilangan_id': 'Jamak (Banyak)',
        'bilangan_en': 'Plural (Jamak)',
        'bilangan_ms': 'Jamak (Ramai)',
        'bilangan_fr': 'Jamak (Pluriel)',
        'posisi_id': 'Nashab/Jar (Objek/Milik)',
        'posisi_en': 'Accusative/Genitive (Object/Possessive)',
        'posisi_ms': 'Nashab/Jar (Objek/Pemilikan)',
        'posisi_fr': 'Nashab/Jar (Objet / Possessif)',
        'keterangan': '...-kalian (banyak laki-laki)'
    },
    '9a': {
        'latin': 'Anti',
        'arti_id': 'KAMU (PR)',
        'arti_en': 'YOU (FEM)',
        'arti_ms': 'ENGKAU / KAMU (PEREMPUAN)',
        'arti_fr': 'TOI / TU (F)',
        'desc_id': 'Kamu / Engkau (1 orang perempuan)',
        'desc_en': 'You (Single Female, 2nd Person)',
        'desc_ms': 'Engkau / Kamu (1 orang perempuan)',
        'desc_fr': 'Toi / Tu (1 personne féminin, 2e personne)',
        'jenis_id': 'Munfashil (Terpisah)',
        'jenis_en': 'Detached (Munfashil)',
        'jenis_ms': 'Munfashil (Berasingan)',
        'jenis_fr': 'Munfashil (Détaché / Isolé)',
        'dhamir_type_id': 'Mukhatab (Orang ke-2)',
        'dhamir_type_en': '2nd Person (Mukhatab)',
        'dhamir_type_ms': 'Mukhatab (Orang ke-2)',
        'dhamir_type_fr': 'Mukhatab (2e personne)',
        'gender_id': 'Muannats (Perempuan)',
        'gender_en': 'Feminine (Muannats)',
        'gender_ms': 'Muannats (Perempuan)',
        'gender_fr': 'Muannats (Féminin)',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': "Rafa' (Subjek)",
        'posisi_en': 'Nominative (Subject)',
        'posisi_ms': "Rafa' (Subjek)",
        'posisi_fr': "Rafa' (Sujet / Nominatif)",
        'keterangan': 'Kamu / Engkau (1 orang perempuan)'
    },
    '9b': {
        'latin': '..ki',
        'arti_id': '..MU (PR)',
        'arti_en': '..YOUR / ..YOU (FEM)',
        'arti_ms': '..MU (PEREMPUAN)',
        'arti_fr': '..TON / ..TOI (F)',
        'desc_id': '...-mu (1 orang perempuan)',
        'desc_en': 'Your / You (Single Female, 2nd Person)',
        'desc_ms': '...-mu (1 orang perempuan)',
        'desc_fr': '...ton / ...toi (1 personne féminin, 2e personne)',
        'jenis_id': 'Muttashil (Tersambung)',
        'jenis_en': 'Attached (Muttashil)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'jenis_fr': 'Muttashil (Attaché / Suffixe)',
        'dhamir_type_id': 'Mukhatab (Orang ke-2)',
        'dhamir_type_en': '2nd Person (Mukhatab)',
        'dhamir_type_ms': 'Mukhatab (Orang ke-2)',
        'dhamir_type_fr': 'Mukhatab (2e personne)',
        'gender_id': 'Muannats (Perempuan)',
        'gender_en': 'Feminine (Muannats)',
        'gender_ms': 'Muannats (Perempuan)',
        'gender_fr': 'Muannats (Féminin)',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': 'Nashab/Jar (Objek/Milik)',
        'posisi_en': 'Accusative/Genitive (Object/Possessive)',
        'posisi_ms': 'Nashab/Jar (Objek/Pemilikan)',
        'posisi_fr': 'Nashab/Jar (Objet / Possessif)',
        'keterangan': '...-mu (1 orang perempuan)'
    },
    '10a': {
        'latin': 'Antunna',
        'arti_id': 'KALIAN (PR)',
        'arti_en': 'YOU ALL (FEM)',
        'arti_ms': 'KAMU SEMUA (PEREMPUAN)',
        'arti_fr': 'VOUS (F PLURIEL)',
        'desc_id': 'Kalian (banyak perempuan)',
        'desc_en': 'You all (Plural Female, 2nd Person)',
        'desc_ms': 'Kamu semua (ramai perempuan)',
        'desc_fr': 'Vous (Pluriel féminin, 2e personne)',
        'jenis_id': 'Munfashil (Terpisah)',
        'jenis_en': 'Detached (Munfashil)',
        'jenis_ms': 'Munfashil (Berasingan)',
        'jenis_fr': 'Munfashil (Détaché / Isolé)',
        'dhamir_type_id': 'Mukhatab (Orang ke-2)',
        'dhamir_type_en': '2nd Person (Mukhatab)',
        'dhamir_type_ms': 'Mukhatab (Orang ke-2)',
        'dhamir_type_fr': 'Mukhatab (2e personne)',
        'gender_id': 'Muannats (Perempuan)',
        'gender_en': 'Feminine (Muannats)',
        'gender_ms': 'Muannats (Perempuan)',
        'gender_fr': 'Muannats (Féminin)',
        'bilangan_id': 'Jamak (Banyak)',
        'bilangan_en': 'Plural (Jamak)',
        'bilangan_ms': 'Jamak (Ramai)',
        'bilangan_fr': 'Jamak (Pluriel)',
        'posisi_id': "Rafa' (Subjek)",
        'posisi_en': 'Nominative (Subject)',
        'posisi_ms': "Rafa' (Subjek)",
        'posisi_fr': "Rafa' (Sujet / Nominatif)",
        'keterangan': 'Kalian (banyak perempuan)'
    },
    '10b': {
        'latin': '..kunna',
        'arti_id': '..KALIAN (PR)',
        'arti_en': '..YOUR / ..YOU ALL (FEM)',
        'arti_ms': '..KAMU SEMUA (PEREMPUAN)',
        'arti_fr': '..VOTRE / ..VOUS (F)',
        'desc_id': '...-kalian (banyak perempuan)',
        'desc_en': 'Your / You all (Plural Female, 2nd Person)',
        'desc_ms': '...-kamu semua (ramai perempuan)',
        'desc_fr': '...votre / ...vous (Pluriel féminin, 2e personne)',
        'jenis_id': 'Muttashil (Tersambung)',
        'jenis_en': 'Attached (Muttashil)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'jenis_fr': 'Muttashil (Attaché / Suffixe)',
        'dhamir_type_id': 'Mukhatab (Orang ke-2)',
        'dhamir_type_en': '2nd Person (Mukhatab)',
        'dhamir_type_ms': 'Mukhatab (Orang ke-2)',
        'dhamir_type_fr': 'Mukhatab (2e personne)',
        'gender_id': 'Muannats (Perempuan)',
        'gender_en': 'Feminine (Muannats)',
        'gender_ms': 'Muannats (Perempuan)',
        'gender_fr': 'Muannats (Féminin)',
        'bilangan_id': 'Jamak (Banyak)',
        'bilangan_en': 'Plural (Jamak)',
        'bilangan_ms': 'Jamak (Ramai)',
        'bilangan_fr': 'Jamak (Pluriel)',
        'posisi_id': 'Nashab/Jar (Objek/Milik)',
        'posisi_en': 'Accusative/Genitive (Object/Possessive)',
        'posisi_ms': 'Nashab/Jar (Objek/Pemilikan)',
        'posisi_fr': 'Nashab/Jar (Objet / Possessif)',
        'keterangan': '...-kalian (banyak perempuan)'
    },

    # --- 3. DHAMIR MUTAKALLIM (ORANG KE-1 / 1ST PERSON / 1RE PERSONNE) ---
    '11a': {
        'latin': 'Anā',
        'arti_id': 'SAYA / AKU',
        'arti_en': 'I / ME',
        'arti_ms': 'SAYA / AKU',
        'arti_fr': 'MOI / JE',
        'desc_id': 'Saya / Aku (Tunggal L/P)',
        'desc_en': 'I / Me (Single 1st Person M/F)',
        'desc_ms': 'Saya / Aku (Tunggal L/P)',
        'desc_fr': 'Moi / Je (Singulier 1re personne M/F)',
        'jenis_id': 'Munfashil (Terpisah)',
        'jenis_en': 'Detached (Munfashil)',
        'jenis_ms': 'Munfashil (Berasingan)',
        'jenis_fr': 'Munfashil (Détaché / Isolé)',
        'dhamir_type_id': 'Mutakallim (Orang ke-1)',
        'dhamir_type_en': '1st Person (Mutakallim)',
        'dhamir_type_ms': 'Mutakallim (Orang ke-1)',
        'dhamir_type_fr': 'Mutakallim (1re personne)',
        'gender_id': 'Mudzakkar / Muannats',
        'gender_en': 'Masculine / Feminine',
        'gender_ms': 'Mudzakkar / Muannats',
        'gender_fr': 'Masculin / Féminin',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': "Rafa' (Subjek)",
        'posisi_en': 'Nominative (Subject)',
        'posisi_ms': "Rafa' (Subjek)",
        'posisi_fr': "Rafa' (Sujet / Nominatif)",
        'keterangan': 'Saya / Aku (Tunggal L/P)'
    },
    '11b': {
        'latin': '..ī / ..ya / ..nī',
        'arti_id': '..KU (AKU/SAYA LK/PR)',
        'arti_en': '..MY / ..ME',
        'arti_ms': '..KU (SAYA/AKU L/P)',
        'arti_fr': '..MON / ..MOI',
        'desc_id': '...-ku (Tunggal L/P)',
        'desc_en': 'My / Me (Single 1st Person M/F)',
        'desc_ms': '...-ku (Tunggal L/P)',
        'desc_fr': '...mon / ...moi (Singulier 1re personne M/F)',
        'jenis_id': 'Muttashil (Tersambung)',
        'jenis_en': 'Attached (Muttashil)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'jenis_fr': 'Muttashil (Attaché / Suffixe)',
        'dhamir_type_id': 'Mutakallim (Orang ke-1)',
        'dhamir_type_en': '1st Person (Mutakallim)',
        'dhamir_type_ms': 'Mutakallim (Orang ke-1)',
        'dhamir_type_fr': 'Mutakallim (1re personne)',
        'gender_id': 'Mudzakkar / Muannats',
        'gender_en': 'Masculine / Feminine',
        'gender_ms': 'Mudzakkar / Muannats',
        'gender_fr': 'Masculin / Féminin',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': 'Nashab/Jar (Objek/Milik)',
        'posisi_en': 'Accusative/Genitive (Object/Possessive)',
        'posisi_ms': 'Nashab/Jar (Objek/Pemilikan)',
        'posisi_fr': 'Nashab/Jar (Objet / Possessif)',
        'keterangan': '...-ku (Tunggal L/P)'
    },
    '12a': {
        'latin': 'Naḥnu',
        'arti_id': 'KAMI / KITA',
        'arti_en': 'WE / US',
        'arti_ms': 'KAMI / KITA',
        'arti_fr': 'NOUS',
        'desc_id': 'Kami / Kita (Jamak L/P)',
        'desc_en': 'We / Us (Plural / Royal 1st Person M/F)',
        'desc_ms': 'Kami / Kita (Jamak / Keagungan L/P)',
        'desc_fr': 'Nous (Pluriel / Pluriel de majesté 1re personne M/F)',
        'jenis_id': 'Munfashil (Terpisah)',
        'jenis_en': 'Detached (Munfashil)',
        'jenis_ms': 'Munfashil (Berasingan)',
        'jenis_fr': 'Munfashil (Détaché / Isolé)',
        'dhamir_type_id': 'Mutakallim (Orang ke-1)',
        'dhamir_type_en': '1st Person (Mutakallim)',
        'dhamir_type_ms': 'Mutakallim (Orang ke-1)',
        'dhamir_type_fr': 'Mutakallim (1re personne)',
        'gender_id': 'Mudzakkar / Muannats',
        'gender_en': 'Masculine / Feminine',
        'gender_ms': 'Mudzakkar / Muannats',
        'gender_fr': 'Masculin / Féminin',
        'bilangan_id': 'Jamak (Banyak/Agung)',
        'bilangan_en': 'Plural / Royal (Jamak)',
        'bilangan_ms': 'Jamak (Ramai/Keagungan)',
        'bilangan_fr': 'Jamak (Pluriel / Majesté)',
        'posisi_id': "Rafa' (Subjek)",
        'posisi_en': 'Nominative (Subject)',
        'posisi_ms': "Rafa' (Subjek)",
        'posisi_fr': "Rafa' (Sujet / Nominatif)",
        'keterangan': 'Kami / Kita (Jamak L/P)'
    },
    '12b': {
        'latin': '..nā',
        'arti_id': '..KAMI / ..KITA',
        'arti_en': '..OUR / ..US',
        'arti_ms': '..KAMI / ..KITA',
        'arti_fr': '..NOTRE / ..NOUS',
        'desc_id': '...-kami / ...-kita (Jamak L/P)',
        'desc_en': 'Our / Us (Plural / Royal 1st Person M/F)',
        'desc_ms': '...-kami / ...-kita (Jamak / Keagungan L/P)',
        'desc_fr': '...notre / ...nous (Pluriel / Pluriel de majesté 1re personne M/F)',
        'jenis_id': 'Muttashil (Tersambung)',
        'jenis_en': 'Attached (Muttashil)',
        'jenis_ms': 'Muttashil (Bersambung)',
        'jenis_fr': 'Muttashil (Attaché / Suffixe)',
        'dhamir_type_id': 'Mutakallim (Orang ke-1)',
        'dhamir_type_en': '1st Person (Mutakallim)',
        'dhamir_type_ms': 'Mutakallim (Orang ke-1)',
        'dhamir_type_fr': 'Mutakallim (1re personne)',
        'gender_id': 'Mudzakkar / Muannats',
        'gender_en': 'Masculine / Feminine',
        'gender_ms': 'Mudzakkar / Muannats',
        'gender_fr': 'Masculin / Féminin',
        'bilangan_id': 'Jamak (Banyak/Agung)',
        'bilangan_en': 'Plural / Royal (Jamak)',
        'bilangan_ms': 'Jamak (Ramai/Keagungan)',
        'bilangan_fr': 'Jamak (Pluriel / Majesté)',
        'posisi_id': 'Nashab/Jar (Objek/Milik)',
        'posisi_en': 'Accusative/Genitive (Object/Possessive)',
        'posisi_ms': 'Nashab/Jar (Objek/Pemilikan)',
        'posisi_fr': 'Nashab/Jar (Objet / Possessif)',
        'keterangan': '...-kami / ...-kita (Jamak L/P)'
    },

    # --- 4. ISIM MAWSHUL (KATA SAMBUNG / RELATIVE PRONOUNS / PRONOMS RELATIFS) ---
    '1': {
        'latin': "Mā",
        'arti_id': 'SESUATU YANG / APA YANG / ORANG YANG',
        'arti_en': 'WHAT / THAT WHICH / WHATEVER',
        'arti_ms': 'APA YANG / SESUATU YANG',
        'arti_fr': 'CE QUI / CE QUE / CE DONT',
        'desc_id': 'Sesuatu yang / Apa yang (untuk benda / non-manusia & umum)',
        'desc_en': 'What / That which / Whatever (For inanimate / non-rational things & general)',
        'desc_ms': 'Apa yang / Sesuatu yang (untuk benda / bukan manusia & umum)',
        'desc_fr': 'Ce qui / Ce que / Ce dont (Pour les choses inanimées et général)',
        'jenis_id': 'Isim Mawshul Musytarak (Umum)',
        'jenis_en': 'Common Relative Pronoun (General)',
        'jenis_ms': 'Isim Mawshul Musytarak (Umum)',
        'jenis_fr': 'Isim Mawshul Musytarak (Général)',
        'dhamir_type_id': 'Isim Mawshul',
        'dhamir_type_en': 'Relative Pronoun',
        'dhamir_type_ms': 'Isim Mawshul',
        'dhamir_type_fr': 'Pronom Relatif (Isim Mawshul)',
        'gender_id': 'Umum (Mudzakkar / Muannats)',
        'gender_en': 'General (Masculine / Feminine)',
        'gender_ms': 'Umum (Mudzakkar / Muannats)',
        'gender_fr': 'Général (Masculin / Féminin)',
        'bilangan_id': 'Umum (Mufrad / Jamak)',
        'bilangan_en': 'General (Singular / Plural)',
        'bilangan_ms': 'Umum (Mufrad / Jamak)',
        'bilangan_fr': 'Général (Singulier / Pluriel)',
        'posisi_id': 'Mabni',
        'posisi_en': 'Indeclinable (Mabni)',
        'posisi_ms': 'Mabni',
        'posisi_fr': 'Invariable (Mabni)',
        'keterangan': 'Sesuatu yang / Apa yang (Benda & Umum)'
    },
    '2': {
        'latin': "Al-Ladzīna",
        'arti_id': 'ORANG-ORANG YANG (LK JAMAK)',
        'arti_en': 'THOSE WHO / THEY WHO (MASC PLURAL)',
        'arti_ms': 'ORANG-ORANG YANG (LELAKI RAMAI)',
        'arti_fr': 'CEUX QUI',
        'desc_id': 'Orang-orang yang (banyak laki-laki / Jamak Mudzakkar)',
        'desc_en': 'Those who / They who (Plural Male, Rational)',
        'desc_ms': 'Orang-orang yang (ramai lelaki / Jamak Mudzakkar)',
        'desc_fr': 'Ceux qui (Pluriel masculin, doués de raison)',
        'jenis_id': 'Isim Mawshul Khashsh (Khusus)',
        'jenis_en': 'Specific Relative Pronoun (Plural Male)',
        'jenis_ms': 'Isim Mawshul Khashsh (Khusus)',
        'jenis_fr': 'Isim Mawshul Khashsh (Spécifique)',
        'dhamir_type_id': 'Isim Mawshul',
        'dhamir_type_en': 'Relative Pronoun',
        'dhamir_type_ms': 'Isim Mawshul',
        'dhamir_type_fr': 'Pronom Relatif (Isim Mawshul)',
        'gender_id': 'Mudzakkar (Laki-laki)',
        'gender_en': 'Masculine (Mudzakkar)',
        'gender_ms': 'Mudzakkar (Lelaki)',
        'gender_fr': 'Mudzakkar (Masculin)',
        'bilangan_id': 'Jamak (Banyak)',
        'bilangan_en': 'Plural (Jamak)',
        'bilangan_ms': 'Jamak (Ramai)',
        'bilangan_fr': 'Jamak (Pluriel)',
        'posisi_id': 'Mabni',
        'posisi_en': 'Indeclinable (Mabni)',
        'posisi_ms': 'Mabni',
        'posisi_fr': 'Invariable (Mabni)',
        'keterangan': 'Orang-orang yang (Banyak Laki-laki)'
    },
    '3': {
        'latin': "Man",
        'arti_id': 'SIAPA YANG / APA YANG / ORANG YANG',
        'arti_en': 'WHO / WHOEVER / THE ONE WHO',
        'arti_ms': 'SESIAPA YANG / ORANG YANG',
        'arti_fr': 'QUI / CELUI QUI / QUICONQUE',
        'desc_id': 'Siapa yang / Orang yang (untuk makhluk berakal / manusia)',
        'desc_en': 'Who / Whoever / The one who (For rational beings / humans)',
        'desc_ms': 'Sesiapa yang / Orang yang (untuk makhluk berakal / manusia)',
        'desc_fr': 'Qui / Quiconque / Celui qui (Pour les êtres doués de raison)',
        'jenis_id': 'Isim Mawshul Musytarak (Berakal)',
        'jenis_en': 'Common Relative Pronoun (Rational)',
        'jenis_ms': 'Isim Mawshul Musytarak (Berakal)',
        'jenis_fr': 'Isim Mawshul Musytarak (Doué de raison)',
        'dhamir_type_id': 'Isim Mawshul',
        'dhamir_type_en': 'Relative Pronoun',
        'dhamir_type_ms': 'Isim Mawshul',
        'dhamir_type_fr': 'Pronom Relatif (Isim Mawshul)',
        'gender_id': 'Umum (Mudzakkar / Muannats)',
        'gender_en': 'General (Masculine / Feminine)',
        'gender_ms': 'Umum (Mudzakkar / Muannats)',
        'gender_fr': 'Général (Masculin / Féminin)',
        'bilangan_id': 'Umum (Mufrad / Jamak)',
        'bilangan_en': 'General (Singular / Plural)',
        'bilangan_ms': 'Umum (Mufrad / Jamak)',
        'bilangan_fr': 'Général (Singulier / Pluriel)',
        'posisi_id': 'Mabni',
        'posisi_en': 'Indeclinable (Mabni)',
        'posisi_ms': 'Mabni',
        'posisi_fr': 'Invariable (Mabni)',
        'keterangan': 'Siapa yang / Orang yang (Makhluk Berakal)'
    },
    '4': {
        'latin': "Al-Ladzī",
        'arti_id': 'ORANG/SESUATU YANG (LK 1)',
        'arti_en': 'THE ONE WHO / WHICH (MASC SINGULAR)',
        'arti_ms': 'ORANG/SESUATU YANG (LELAKI SEORANG)',
        'arti_fr': 'CELUI QUI / LEQUEL',
        'desc_id': 'Orang yang / Sesuatu yang (1 orang laki-laki / Mufrad Mudzakkar)',
        'desc_en': 'The one who / Which (Single Male, Masculine Singular)',
        'desc_ms': 'Orang yang / Sesuatu yang (1 orang lelaki / Mufrad Mudzakkar)',
        'desc_fr': 'Celui qui / Lequel (1 personne masculin, singulier)',
        'jenis_id': 'Isim Mawshul Khashsh (Khusus)',
        'jenis_en': 'Specific Relative Pronoun (Singular Male)',
        'jenis_ms': 'Isim Mawshul Khashsh (Khusus)',
        'jenis_fr': 'Isim Mawshul Khashsh (Spécifique)',
        'dhamir_type_id': 'Isim Mawshul',
        'dhamir_type_en': 'Relative Pronoun',
        'dhamir_type_ms': 'Isim Mawshul',
        'dhamir_type_fr': 'Pronom Relatif (Isim Mawshul)',
        'gender_id': 'Mudzakkar (Laki-laki)',
        'gender_en': 'Masculine (Mudzakkar)',
        'gender_ms': 'Mudzakkar (Lelaki)',
        'gender_fr': 'Mudzakkar (Masculin)',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': 'Mabni',
        'posisi_en': 'Indeclinable (Mabni)',
        'posisi_ms': 'Mabni',
        'posisi_fr': 'Invariable (Mabni)',
        'keterangan': 'Orang yang / Yang (1 Laki-laki)'
    },
    '5': {
        'latin': "Ayy",
        'arti_id': 'YANG MANA / SIAPA SAJA YANG',
        'arti_en': 'WHICHEVER / WHOEVER / WHICH',
        'arti_ms': 'YANG MANA / SESIAPA SAHAJA YANG',
        'arti_fr': 'LEQUEL / QUEL QUE SOIT',
        'desc_id': 'Yang mana saja / Siapa saja yang (Umum Mudzakkar)',
        'desc_en': 'Whichever / Whoever / Which (Masculine General)',
        'desc_ms': 'Yang mana sahaja / Sesiapa sahaja yang (Umum Mudzakkar)',
        'desc_fr': 'Lequel / Quiconque / Quel que soit (Masculin général)',
        'jenis_id': 'Isim Mawshul Musytarak (Umum)',
        'jenis_en': 'Common Relative Pronoun (General)',
        'jenis_ms': 'Isim Mawshul Musytarak (Umum)',
        'jenis_fr': 'Isim Mawshul Musytarak (Général)',
        'dhamir_type_id': 'Isim Mawshul',
        'dhamir_type_en': 'Relative Pronoun',
        'dhamir_type_ms': 'Isim Mawshul',
        'dhamir_type_fr': 'Pronom Relatif (Isim Mawshul)',
        'gender_id': 'Mudzakkar (Laki-laki / Umum)',
        'gender_en': 'Masculine / General',
        'gender_ms': 'Mudzakkar (Lelaki / Umum)',
        'gender_fr': 'Mudzakkar (Masculin / Général)',
        'bilangan_id': 'Mufrad / Umum',
        'bilangan_en': 'Singular / General',
        'bilangan_ms': 'Mufrad / Umum',
        'bilangan_fr': 'Mufrad (Singulier / Général)',
        'posisi_id': "Mu'rab (Dapat Berubah Harakat)",
        'posisi_en': 'Declinable (Mu\'rab)',
        'posisi_ms': "Mu'rab (Boleh Berubah Baris)",
        'posisi_fr': "Variable (Mu'rab)",
        'keterangan': 'Yang mana / Siapa saja yang'
    },
    '6': {
        'latin': "Al-Latī",
        'arti_id': 'ORANG/SESUATU YANG (PR 1)',
        'arti_en': 'THE ONE WHO / WHICH (FEM SINGULAR)',
        'arti_ms': 'ORANG/SESUATU YANG (PEREMPUAN SEORANG)',
        'arti_fr': 'CELLE QUI / LAQUELLE',
        'desc_id': 'Orang yang / Sesuatu yang (1 orang perempuan / Mufrad Muannats)',
        'desc_en': 'The one who / Which (Single Female, Feminine Singular)',
        'desc_ms': 'Orang yang / Sesuatu yang (1 orang perempuan / Mufrad Muannats)',
        'desc_fr': 'Celle qui / Laquelle (1 personne féminin, singulier)',
        'jenis_id': 'Isim Mawshul Khashsh (Khusus)',
        'jenis_en': 'Specific Relative Pronoun (Singular Female)',
        'jenis_ms': 'Isim Mawshul Khashsh (Khusus)',
        'jenis_fr': 'Isim Mawshul Khashsh (Spécifique)',
        'dhamir_type_id': 'Isim Mawshul',
        'dhamir_type_en': 'Relative Pronoun',
        'dhamir_type_ms': 'Isim Mawshul',
        'dhamir_type_fr': 'Pronom Relatif (Isim Mawshul)',
        'gender_id': 'Muannats (Perempuan)',
        'gender_en': 'Feminine (Muannats)',
        'gender_ms': 'Muannats (Perempuan)',
        'gender_fr': 'Muannats (Féminin)',
        'bilangan_id': 'Mufrad (Tunggal)',
        'bilangan_en': 'Singular (Mufrad)',
        'bilangan_ms': 'Mufrad (Tunggal)',
        'bilangan_fr': 'Mufrad (Singulier)',
        'posisi_id': 'Mabni',
        'posisi_en': 'Indeclinable (Mabni)',
        'posisi_ms': 'Mabni',
        'posisi_fr': 'Invariable (Mabni)',
        'keterangan': 'Orang yang / Yang (1 Perempuan)'
    },
    '10': {
        'latin': "Ayyatu",
        'arti_id': 'YANG MANA (PR)',
        'arti_en': 'WHICHEVER (FEM)',
        'arti_ms': 'YANG MANA (PEREMPUAN)',
        'arti_fr': 'LAQUELLE (F)',
        'desc_id': 'Yang mana saja (Bentuk Perempuan / Muannats)',
        'desc_en': 'Whichever / Which (Feminine)',
        'desc_ms': 'Yang mana sahaja (Bentuk Perempuan / Muannats)',
        'desc_fr': 'Laquelle / Quelle que soit (Féminin)',
        'jenis_id': 'Isim Mawshul Musytarak (Muannats)',
        'jenis_en': 'Common Relative Pronoun (Feminine)',
        'jenis_ms': 'Isim Mawshul Musytarak (Muannats)',
        'jenis_fr': 'Isim Mawshul Musytarak (Féminin)',
        'dhamir_type_id': 'Isim Mawshul',
        'dhamir_type_en': 'Relative Pronoun',
        'dhamir_type_ms': 'Isim Mawshul',
        'dhamir_type_fr': 'Pronom Relatif (Isim Mawshul)',
        'gender_id': 'Muannats (Perempuan)',
        'gender_en': 'Feminine (Muannats)',
        'gender_ms': 'Muannats (Perempuan)',
        'gender_fr': 'Muannats (Féminin)',
        'bilangan_id': 'Mufrad / Umum',
        'bilangan_en': 'Singular / General',
        'bilangan_ms': 'Mufrad / Umum',
        'bilangan_fr': 'Mufrad (Singulier / Général)',
        'posisi_id': "Mu'rab (Dapat Berubah Harakat)",
        'posisi_en': 'Declinable (Mu\'rab)',
        'posisi_ms': "Mu'rab (Boleh Berubah Baris)",
        'posisi_fr': "Variable (Mu'rab)",
        'keterangan': 'Yang mana saja (Bentuk Perempuan)'
    }
}

def generate():
    raw_data_path = os.path.join(BASE_DIR, 'dhamir_data.json')
    en_trans_path = os.path.join(BASE_DIR, 'en_translations.json')
    ms_trans_path = os.path.join(BASE_DIR, 'ms_translations.json')
    fr_trans_path = os.path.join(BASE_DIR, 'fr_translations.json')

    with open(raw_data_path, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)

    with open(en_trans_path, 'r', encoding='utf-8') as f:
        en_trans = json.load(f)

    with open(ms_trans_path, 'r', encoding='utf-8') as f:
        ms_trans = json.load(f)

    with open(fr_trans_path, 'r', encoding='utf-8') as f:
        fr_trans = json.load(f)

    for item in raw_data:
        s_no = int(item['SURAT']) if item.get('SURAT') is not None else None
        a_no = int(item['AYAT']) if item.get('AYAT') is not None else None
        verse_key = f"{s_no}:{a_no}"

        b = (item.get('Bentuk Kata') or '1. Dhamir').strip()
        if b.startswith('1.') or 'dhamir' in b.lower():
            item['BentukKataID'] = '1. Dhamir (Kata Ganti)'
            item['BentukKataEN'] = '1. Pronouns (Dhamir)'
            item['BentukKataMS'] = '1. Dhamir (Kata Ganti Nama)'
            item['BentukKataFR'] = '1. Pronoms (Dhamir)'
        elif b.startswith('2.') or 'mawshul' in b.lower():
            item['BentukKataID'] = '2. Mawshul (Kata Sambung)'
            item['BentukKataEN'] = '2. Relative Pronouns (Mawshul)'
            item['BentukKataMS'] = '2. Mawshul (Kata Hubung)'
            item['BentukKataFR'] = '2. Pronoms Relatifs (Mawshul)'

        if s_no and s_no in SURAHS:
            item['SuratNama'] = SURAHS[s_no]['nama']
            item['SuratArab'] = SURAHS[s_no]['arab']
            item['SuratArti'] = SURAHS[s_no]['arti_id']
            item['SuratArtiID'] = SURAHS[s_no]['arti_id']
            item['SuratArtiEN'] = SURAHS[s_no]['arti_en']
            item['SuratArtiMS'] = SURAHS[s_no]['arti_ms']
            item['SuratArtiFR'] = SURAHS[s_no]['arti_fr']
        else:
            item['SuratNama'] = f'Surat {s_no}'
            item['SuratArab'] = ''
            item['SuratArti'] = ''
            item['SuratArtiID'] = ''
            item['SuratArtiEN'] = ''
            item['SuratArtiMS'] = ''
            item['SuratArtiFR'] = ''

        nk = str(item.get('No kata', '')).strip()
        if nk in GRAMMATICAL_METADATA:
            gm = GRAMMATICAL_METADATA[nk]
            item['Grammar'] = gm
            item['Latin'] = gm['latin']
            item['ArtiKataID'] = gm['arti_id']
            item['ArtiKataEN'] = gm['arti_en']
            item['ArtiKataMS'] = gm['arti_ms']
            item['ArtiKataFR'] = gm['arti_fr']

        # Set Verse Translations
        item['TeksArtiID'] = item.get('TeksArtiID') or item.get('TeksArti', '')
        item['TeksArtiEN'] = en_trans.get(verse_key, item.get('TeksArtiEN', item.get('TeksArti', '')))
        item['TeksArtiMS'] = ms_trans.get(verse_key, item.get('TeksArtiMS', item.get('TeksArti', '')))
        item['TeksArtiFR'] = fr_trans.get(verse_key, item.get('TeksArtiFR', item.get('TeksArti', '')))

    js_content = f'''/**
 * Data Dhamir Al-Qur'an & Kamus Surah (Multilingual: Indonesia 🇮🇩, English 🇬🇧, Melayu 🇲🇾, Français 🇫🇷)
 * Terjemahan:
 * - ID: Kementerian Agama RI (Kemenag)
 * - EN: Sahih International
 * - MS: Syeikh Abdullah Muhammad Basmeih (JAKIM)
 * - FR: Muhammad Hamidullah (Le Saint Coran)
 */
const DHAMIR_DATA = {json.dumps(raw_data, ensure_ascii=False, indent=2)};

const SURAH_DICT = {json.dumps(SURAHS, ensure_ascii=False, indent=2)};

const GRAMMAR_INFO = {json.dumps(GRAMMATICAL_METADATA, ensure_ascii=False, indent=2)};
'''

    out_js = os.path.join(BASE_DIR, 'dhamir_data.js')
    out_json = os.path.join(BASE_DIR, 'dhamir_data.json')

    with open(out_js, 'w', encoding='utf-8') as f:
        f.write(js_content)

    with open(out_json, 'w', encoding='utf-8') as f:
        json.dump(raw_data, f, ensure_ascii=False, indent=2)

    print(f"Berhasil menghasilkan dhamir_data.js & json multilingual dengan {len(raw_data)} entri!")

if __name__ == '__main__':
    generate()
